### ISSUE TITLE
Partial determinism of the descendant selector (..)

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#103]
At today's meeting, I agreed to submit a PR to float the idea of partial determinism for the descendants operator, even though the consensus seems to be against any determinism for that operator. Given the descendants operator PR https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/102 isn't yet merged, I'll start with an issue to capture discussion and avoid rebasing effort.

We probably don't want to _force_ any determinism on implementations, so the idea is to provide a recommendation for implementations which want to provide partial determinism and use "SHOULD" language so the recommendation is optional. Then implementations which opt in will agree on the ordering recommentations.

The benefits of partial determinism are:
* improved predictability and interoperation
* relative ease for JSONPath users writing tests, as there are fewer possible outputs.

In PR https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/102 there are no constraints on the non-determinism of the descendants operator:
> The `descendant-selector` is inspired by ECMAScript for XML (E4X). It selects the node and all its descendants.

We agreed in issue https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/60 to allow non-determinism in the order in which objects are iterated and the same should be true when the descendants operator encounters an object. But there are other details of the ordering which could be tied down:
* arrays SHOULD be visited in array order
* nodes SHOULD be visited strictly before their descendants (so-called _pre-order_ traversal).

(_Post-order_ traversal, in which nodes are visited strictly after their descendants, would be an equally valid alternative.)

One of the reasons given at today's meeting for allowing full non-determinism was for parallel processing, so it would be interesting to discuss what constraints the above rules produce on parallel processing. The order of collection of the results seems to be more significant than whether or not parallel processing is used.

**Comment by gregsdennis** [comment]
My preference is _pre-order_ traversal (node then descendants).

> One of the reasons given at today's meeting for allowing full determinism was for parallel processing...

Do you mean "... for _not requiring_ full determinism..."?  Full determinism would be requiring a specified ordering, but what we're saying is that we _don't_ want that because parallel processing can't guarantee it.

**Comment by glyn** [comment]
Yes, I meant to write "... for allowing full non-determinism ...".

**Comment by glyn** [comment]
> nodes SHOULD be visited strictly before their descendants

Given that each node has either a single value or is an array or an object, the above statement doesn't mean much, since `..` doesn't visit array indices or object keys.

So the constraints boil down to "arrays SHOULD be visited in array order".

**Comment by gregsdennis** [comment]
That's not quite correct.  `..` adds objects and arrays to the result set as well as their children.  This is just saying they're added _before_ their children.

**Comment by glyn** [comment]
Yes, my mistake. Not doing too well with this issue so far..

**Comment by glyn** [comment]
@gregsdennis This issue is now a bit of a mess. I'd like to fix the OP and then IMO it would be good to delete all the other comments except for your ordering preference in https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/103#issuecomment-865899040. wdyt?

**Comment by gregsdennis** [comment]
I think put a summary at the top, then a line break and then leave what's there. I'd prefer to retain the history.

I don't think it's a mess, though.  I think it's fine to leave as is.

**Comment by cabo** [comment]
Except that I don't know what's "SHOULD" about that, I agree with these partial ordering guidelines.

If we want to introduce different compliance levels, that is fine, but it SHOULD :-) not be coupled to using the term SHOULD vs. MUST.
"Full compliance requires..."
vs. "For conditional compliance, at least..."

**Comment by glyn** [comment]
I probably misunderstood [RFC 2119](https://datatracker.ietf.org/doc/html/rfc2119), or applied it atypically. I am comfortable with using @cabo's compliance level language instead.

**Comment by gregsdennis** [comment]
We need to be careful here that we don't optimize for tests.  It seems to be a focus of this discussion that we want to make verification of output in the test suite easier.

Rather, we need to focus on supportability and interoperability.  If that aligns with running the test, that's good.  But don't let making running the tests easier at the cost of making things significantly more difficult for implementors.

It's non-trivial, but also not very complex, to verify unordered sets of nodes in output.

**Comment by glyn** [comment]
More significant than complications for the JSONPath test suite is the
amount of non-determinism that tests of code which uses JSONPath will have
to accommodate.

**Comment by timbray** [comment]
I recommend checking out the language around interoperability in 8259. Something like that might work here.

**Comment by glyn** [comment]
I'm having a hard time judging the consensus, or lack of it, here. Regardless of the detailed language, please could interested parties indicate which of these options they favour:

A.  Don't tie down the non-determinism of `..` at all
B. Require `..` to visit arrays in array order and visit nodes before their descendants
C. Some other option involving B with the option of A or A with the option of B, using some kind of language TBD.

/cc @goessner

**Comment by cabo** [comment]
> I recommend checking out the language around interoperability in 8259. Something like that might work here.

I’m not sure you actually mean that, but for me that would be about the worst result we could arrive at.

8259 was worked on in a politicized context, which simply didn’t allow us to clean it up.  There barely was the courage to finally say that interchanging JSON implies UTF-8, which was at least some progress.
But there was no way to clarify the data model issues, and this is why JSON in practice essentially has been reduced to I-JSON, which is not bad at all, but really different from what JSON originally promised to be.

I’d prefer if we don’t need an I-JSONPath document to clean up the interoperability issues left in JSONPath-base.

Given that we have JSON and I-JSON, it may be useful to acknowledge (or violently reject! — we get to choose) the emergence of multiple levels/classes of interoperability with JSONPath, too.

Grüße, Carsten

**Comment by remorhaz** [comment]
> B. Require .. to visit arrays in array order and visit nodes before their descendants

I would vote for this option, but in the same time we have slices with negative steps, which naturally do sort of "backwards" iteration in Python. If we determine order of array items visiting (thus determining the order of selected nodes in output), shouldn't we also take into consideration the effect of selectors, and if yes - then should the order of union items affect the order of visit?

**Comment by glyn** [comment]
@remorhaz I don't follow. The ordering of `..` is not affected by other selectors (e.g. involving negative array steps or unions).

**Comment by remorhaz** [comment]
> The ordering of .. is not affected by other selectors (e.g. involving negative array steps or unions).

This is not absolutely clear for me. Let us have the following structure:
```json
[
  [
    [1, 2, 3, 4],
    [5, 6, 7, 8]
  ]
]
```
And we apply `$..[::-1]` query. At first we apply `..` selector to the root node, and it returns following nodes:

1. `$[0]`: `[[1, 2, 3, 4], [5, 6, 7, 8]]`
2. `$[0][0]`: `[1, 2, 3, 4]`
3. `$[0][0][0]`: `1`
4. `$[0][0][1]`: `2`
5. `$[0][0][2]`: `3`
6. `$[0][0][3]`: `4`
7.  `$[0][1]`: `[5, 6, 7, 8]`
8. `$[0][1][0]`: `5`
9. `$[0][1][1]`: `6`
10. `$[0][1][2]`: `7`
11. `$[0][1][3]`: `8`

Then we apply `[::-1]` selector to each these nodes. Applying slice to number will return empty node list, so I consider only arrays below:

`$[0]`: `[[1, 2, 3, 4], [5, 6, 7, 8]]`
1. `$[0][1]`: `[5, 6, 7, 8]`
2. `$[0][0]`: `[1, 2, 3, 4]`

`$[0][0]`: `[1, 2, 3, 4]`
1. `$[0][0][3]`: `4`
2. `$[0][0][2]`: `3`
3. `$[0][0][1]`: `2`
4. `$[0][0][0]`: `1`

`$[0][1]`: `[5, 6, 7, 8]`
1. `$[0][1][3]`: `4`
2. `$[0][1][2]`: `3`
3. `$[0][1][1]`: `2`
4. `$[0][1][0]`: `1`

The resulting node list is:
1. `$[0][1]`: `[5, 6, 7, 8]`
2. `$[0][0]`: `[1, 2, 3, 4]`
3. `$[0][0][3]`: `4`
4. `$[0][0][2]`: `3`
5. `$[0][0][1]`: `2`
6. `$[0][0][0]`: `1`
7. `$[0][1][3]`: `4`
8. `$[0][1][2]`: `3`
9. `$[0][1][1]`: `2`
10. `$[0][1][0]`: `1`

I've didn't notice any problems following both "natural order" while applying `..` and "reversed order" while applying `[::-1]`, because they never apply simultaneously. Please show me if I missed something in my reasoning.

**Comment by remorhaz** [comment]
The idea of determinism in arrays itself seems important to me. For example, let some service provides array of some data in some garanteed order that is important for end user, and and another service wants to use JSONPath to filter them on some fancy condition.

If JSONPath provides determined order of results, then it's at least possible to solve the problem with a single query. If no - we'll have no easy way to do it. We will need to extract from JSON original order somehow (with alternative tool or manual parsing), and then use it to rebuild original order of filtered items. It will be much more convenient to receive results in a determined order.

**Comment by timbray** [comment]
The main aspect of JSON that leads to non-determinism is the fact that no
specification makes any guarantee that the order of Members in an Object
carries any meaning. RFC8259, last para of Section 4
<https://datatracker.ietf.org/doc/html/rfc8259#section-4>,  explicitly
cautions against relying on this.

On the other hand, order in arrays is explicitly significant and I would be
shocked if application of array-based selectors did not produce identical
results in all implementations.

Or am I missing something obvious?

**Comment by glyn** [comment]
Yes, I think we agree that array order should be preserved and that object order is not guaranteed, but I'd like this issue to focus specifically on the ordering of `..`.

**Comment by gregsdennis** [comment]
Added text indicating node-first / children-second ordering.

**Comment by glyn** [comment]
... and preserving array order.

**Comment by gregsdennis** [comment]
Sure. That too.  But I don't think that was ever in question.
