### ISSUE TITLE
Generalise filter comparisons

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#112]
Currently, filter comparison require a path on the left hand side and a constant expression on the right hand side.  This seems overly restrictive. We should generalise it to allow the opposite order as well as path to path comparisons and, for completeness, constant expression to constant expression comparisons.

For example, the following comparisons should be valid:
```
@.foo == 1
1 == @.foo
@.foo == @.bar
1 == 1
```

**Comment by cabo** [comment]
Should `=~` be symmetric, too?

**Comment by glyn** [comment]
Did you mean `~=` (which is what we use in the current draft)?

I think not because its operands have distinct types and it's probably easier to police restrictions and give good diagnostics if we keep `~=` asymmetric. For instance, with the current syntax:
```
@.foo ~= @.bar
```
can fail with an error such as "@.bar needs to be a regular expression literal", which is a bit easier to understand than something like "one side of ~= needs to be a regular expression literal".

Having said that, other generalisations of `~=` may be worth it, such as allowing a string literal (rather than only a path) on the left hand side, for consistency with the above syntax for the other comparison operators, but even that could be give rise to confusion, e.g.:
```
"/.*/" ~= /.*/
```

**Comment by cabo** [comment]
Oops.  It really should be `=~`.

Perl introduced `=~` as `string =~ regexp` (where regexp actually could be a substitute operator etc.).
Ruby generalized this to `regexp =~ string` and `string =~ regexp`.
Java, JavaScript, Python, PowerShell don't have an operator at all; this is all handled using method calls.

So if we want to have syntax for regexp matching, we probably want to go with Perl's.
We also need to discuss whether we need syntax for regexp literals.
But this is maybe leading beyond this github issue.

**Comment by goessner** [comment]
Convinced ... you made the point.
