### ISSUE TITLE
Operator precedence table

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#113]
Introducing an operator precedence table will help us comunicate what we are trying to achieve precedence-wise in the ABNF syntax.

_Originally posted by @cabo in https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/111#issuecomment-892618964_

**Comment by goessner** [comment]
Here is a first version ... taken from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_Precedence)

| Precedence | Operator type | Syntax | Comment |
|:--:|:--:|:--:|:--:|
|  6  | Grouping | `(...)` |  | 
|  5  | Logical NOT | `!` |  | 
|  4  | Less Than<br>Greater Than<br>Less Than Or Equal<br>Greater Than Or Equal | `<`<br>`>`<br>`<=`<br>`>=` | Relation | 
|  3  | Equal To<br>Not Equal To | `==`<br>`!=` | Comparison | 
|  2  | Logical AND | `&&` |  | 
|  1  | Logical OR | `\|\|` |  |

**Comment by glyn** [comment]
Thanks for that @goessner!

I suggest we combine the third and fourth rows and give `==` and `!=` the same precedence as the other comparison operators as I don't think there is a situation where their relative precedence is necessary.

Also, having a separate row for `==` and `!=` gives the impression we want to entertain expressions such as:
```
@.foo < 2 == @.bar
```
and
```
1 < 2 == 2 < 3
```
which I'd prefer to avoid

**Comment by goessner** [comment]
Yes ... so ...

| Precedence | Operator type | Syntax | Comment |
|:--:|:--:|:--:|:--:|
|  5  | Grouping | `(...)` |  | 
|  4  | Logical NOT | `!` |  | 
|  3  | Equal To<br>Not Equal To<br>Less Than<br>Greater Than<br>Less Than Or Equal<br>Greater Than Or Equal | `==`<br>`!=`<br>`<`<br>`>`<br>`<=`<br>`>=` | Comparison | 
|  2  | Logical AND | `&&` |  | 
|  1  | Logical OR | `\|\|` |  |
