### ISSUE TITLE
key missing vs key present with null

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#118]
A new [StackOverflow question](https://stackoverflow.com/q/69069083/878701) highlights the need to define whether these two cases are the same or different:

- a key missing
- a key present but with `null` as a value

I would expect that Javascript would handle these cases differently, but .Net generally wouldn't (it seems Newtonsoft has some special handling for this).

Posed in a more direct, testable way, given the data

```json
[
  {
      "id": 2
  }
]
```

would

```
$[?(@.foo==null)]
```

return any results?

(related to #64 and #47)

**Comment by cburgmer** [comment]
I think the corresponding test in the comparison project is https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_equals_null.html. Currently no consensus exists.

**Comment by danielaparker** [comment]
I think this is related to [\#74](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/74). Or, what does the left hand side of `@.foo==null` mean? It means different things in different implementations. 

For JSONPath implementations in interpreted languages such as JavaScript, Python or PHP, and whose filter expressions are these languages, `@.foo` means whatever it means in these languages. In some of these languages it evaluates to `null` when there is no match, in others `false`, and in others it's a type error. 

For implementations such as Jaway where `@.foo` means a JSONPath expression that returns a single JSON value (rather than an array of values), it depends on what the implementation specifies `@.foo` to evaluate to when there is no match. For some, it's `null`, for others `false`, and for others it's a type error.  

In [JMESPath](https://jmespath.org/), for comparison, evaluating an object with a missing key is specified to return a null value, so 
```
[?foo==null]
```
returns
```
[  { "id": 2 }]
```

**Comment by gregsdennis** [comment]
Yes, it does relate to that as well!.

**Comment by danielaparker** [comment]
> Yes, it does relate to that as well! I interpret literals as JSON values.

And specifically related to https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/64#issuecomment-831755108

**Comment by danielaparker** [comment]
> > Yes, it does relate to that as well! I interpret literals as JSON values.
> 
> That and [#64 (comment)](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/64#issuecomment-831755108)

In any case, it's impossible to talk about what 
```
?(@.foo==null)
```
means without first defining what `@.foo` means and what `==` means. 

Daniel

**Comment by gregsdennis** [comment]
@danielaparker you're getting a little ahead of yourself. Operators and relative paths in expressions are discussed in other issues that deal with expressions themselves. These are quite well-defined in those issues.

**Comment by danielaparker** [comment]
@gregsdennis, just noting that the answer to this issue you raised follows immediately once the meaning of `@.foo` and `==` have been defined. Nothing more.

**Comment by cabo** [comment]
> @gregsdennis, just noting that the answer to this issue you raised follows immediately once the meaning of `@.foo` and `==` have been defined. Nothing more.

Indeed, so the discussion here should inform the decisions we make for empty `@.foo` and for `==`.

**Comment by goessner** [comment]
The latest draft seems to be pretty clear about that.

https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#name-filter-selector

> A member or element value by itself is falsy only, if it does not exist. Otherwise it is truthy, resulting in its value. To be more specific explicit comparisons are necessary. This existence test -- as an exception of the general rule -- also works with complex values.

Problem here is, that JSON lacks  `undefined ` value (from JavaScript). So we decided to use standalone path expressions in filters as existence tests

* `[?@foo]` ... selected, if member `foo` exists.
*  `[?(!@foo)]` ... selected, if member `foo` does not exists.
*  but `[?(!!@foo)]` ... selected, if value of  `foo` is truthy.
* `[?(@foo == null)]` ... selected only, if member exactly has that value.
*  `[?(!@foo == true)]` ... not allowed with comparison, rather use  `[?(@foo != true)]`.

Using new `in` operator also allows test for existence now as with `[?('foo' in @)]`.

Most of discussions were done in this pull request

https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/111

Am I missing something here?

-- sg

**Comment by danielaparker** [comment]
> The latest draft seems to be pretty clear about that.
> 
> https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#name-filter-selector
> 
> Most of discussions were done in this pull request
> 
> #111
> 
> Am I missing something here?
> 
What's missing, and what's missing generally in the draft, is any survey and analysis of prior experience in the great physical tarpit that is JSONPath. And if the purpose of this IETF effort really is to standardize existing practice, I think that's important. Of course, if that's not the purpose, than it doesn't matter, but everybody says that's the purpose.

It's not that the rules you've sketched here cannot be motivated by some prior experience, see e.g my analysis [here] (https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/119#issuecomment-919628694). 11 of 42 implementations, including two that may be considered important,  do follow this rule:

[?@.foo] ... selected, if member foo exists.

But Goessner Javascript doesn't follow that rule. Nor do a significant number of others. 

If the draft really is about standardizing existing behaviour, it seems to me that it needs to justify its choices with reference to prior experience.

**Comment by goessner** [comment]
hmm ... in my original proposal I included (as already someone mentioned):

```
//book[isbn]   | $..book[?(@.isbn)]   |  filter all books with isbn number |
```
It seems to be, this was of no significant relevance for existing implementations.

**Comment by gregsdennis** [comment]
@goessner would your implementation match on `isbn: null`?

**Comment by goessner** [comment]
of course it would ... as I reused the Javascript engine for simplicity then.

**Comment by danielaparker** [comment]
@goessner, maybe I've misunderstood Greg's question, but  using Goessner Javascript, and given the JSON document
```
{
    "store": {
        "book": [
            {
                "isbn" : null
            }
    ]
  }
}
``` 
the query
```
$..[?(@.isbn)]
```
returns nothing. This is what we expect from JavaScript, and is consistent with the results reported [here](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/119#issuecomment-919628694).

**Comment by danielaparker** [comment]
> hmm ... in my original proposal I included (as already someone mentioned):
> 
> ```
> //book[isbn]   | $..book[?(@.isbn)]   |  filter all books with isbn number |
> ```
> 
> It seems to be, this was of no significant relevance for existing implementations.

I don't think any of the JSONPath implementations that use a dynamic language for evaluation, whether JavaScript,  PHP, Python, Ruby or Lua, evaluate `?(@.isbn)` that way. They all evaluate `@.isbn` first and then apply "not falsey" rules of one sort or another to the result. That's a lot of implementations, including the original.

On the other hand a significant number of implementations that implemented their own expression evaluators do evaluate  `?(@.isbn)` that way. Including Jayway JsonPath.

**Comment by cabo** [comment]
> If the draft really is about standardizing existing behaviour, it seems to me that it needs to justify its choices with reference to prior experience. Not just with what "we" (a handful of people) "agreed".

The charter is quite specific:

> The WG will develop a standards-track JSONPath specification that
is technically sound and complete, based on the common semantics
and other aspects of existing implementations. Where there are
differences, the working group will analyze those differences and
make choices that rough consensus considers technically best, with
an aim toward minimizing disruption among the different JSONPath
implementations.

Since we do have those differences here, we are asked to consider what is "technically best", but "with an aim toward minimizing disruption".  This seems clear to me, and I think our charter writers did a very good job here.

**Comment by danielaparker** [comment]
> Since we do have those differences here, we are asked to consider what is "technically best", but "with an aim toward minimizing disruption". This seems clear to me, and I think our charter writers did a very good job here.

I think it's hard to make a case that the draft is doing much to minimize disruption.

On the one hand, it's becoming incompatible with all of the implementations that use a dynamic language such as Javascript, PHP, Python, Ruby or Lua for evaluating expressions. For users of such implementations, having an expression language in their familiar language, with all of the functions that that language provides, is part of the appeal of these implementations. 

On the other hand, the WG is sketching out an expression language that is different from the expression languages that were developed by other implementations mostly following Jayway. These expression languages specified `@.relative-path` as a JSONPath expression, with rules for "ExecuteSingle" to produce a single value for use in comparisons. `@.` means something different in the draft, where it's not a JSONPath expression.

It seems to me that the draft is departing from both streams of JSONPath that evolved from the original article. I don't see anything in the draft that suggests that the editors consider prior experience important. There is no text in the draft that discusses the important implementations, and which features were motivated by one, which from another, and which are new or refinements.

Anyway, I realize that nobody here is interested in this topic, no doubt for the obvious reason :-)

**Comment by glyn** [comment]
Daniel wrote:
> I don't see anything in the draft that suggests that the editors consider
prior experience important. There is no text in the draft that discusses
the important implementations,
> and which features were motivated by one, which from another, and which
are new or refinements.

I consider prior experience to be very important and I'm sure Stefan does
too. However, I am not sure to what extent the spec should reference
particular implementations since such references will not necessarily stand
the test of time. Perhaps an appendix is the way to do it, in which case,
please feel free to submit a PR to help lead the way forward. Editors need
not be the only authors.

>

> Anyway, I realize that nobody here is interested in this topic, no doubt
for the obvious reason :-)

Not so.

**Comment by gregsdennis** [comment]
I agree that such references do not belong in the main text of the spec. An appendix is okay. If I had my way, if have a separate companion doc that summarized individual decisions and the reasoning behind them.  Such a document would be a natural place to include references to behaviors in existing implementations.

**Comment by danielaparker** [comment]
@glyn wrote

> Perhaps an appendix is the way to do it, in which case, please feel free to submit a PR to help lead the way forward. 

If the purpose of the WG is to standardize existing behavior, as they say it is, I think it's up to the authors to justify how the specified behavior relates to prior experience.

**Comment by cabo** [comment]
Sent from mobile, sorry for terse

> On 24. Sep 2021, at 14:53, Daniel Parker ***@***.***> wrote:
> 
> If the purpose of the WG is to standardize existing behavior

It’s not. Please reread the charter. 

RFC 2418 talks more about the role of authors (ie to implement the directions of the WG), and I’m certain the authors will do that. If the WG wants to have a big rationale section to document their decisions beyond what feels natural for the authors, all I can say is “send text”…

**Comment by danielaparker** [comment]
> Sent from mobile, sorry for terse
> On 24. Sep 2021, at 14:53, Daniel Parker ***@***.***> wrote: If the purpose of the WG is to standardize existing behavior
> It’s not. 

Thanks for the clarification.

**Comment by cabo** [comment]
Fixed in 76789d8

**Comment by gregsdennis** [comment]
Can you summarize the resolution, please?

**Comment by cabo** [comment]
Since 76789d8, Section 3.5.9 now says:

```
   *  A member or element value by itself in a Boolean context is
      interpreted as false only if it does not exist.  Otherwise it is
      interpreted as true.  To be more specific about the actual value,
      explicit comparisons are necessary.  This existence test -- as an
      exception to the general rule -- also works with structured
      values.
```
