### ISSUE TITLE
Is absent equal to absent?

### ISSUE THREAD

**Issue by cabo** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#123]
If yes,

`@.doesnotexist != @.alsodoesnotexist` 

is false.

Need to discuss impact on >, >=, etc.

See also:
https://notes.ietf.org/notes-ietf-interim-2021-jsonpath-03-jsonpath

**Comment by cburgmer** [comment]
I've extended the query which compares two paths via equals to include absent keys: https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_equals_with_path_and_path.html. No consensus, not even a majority at this point.

**Comment by cabo** [comment]
... which is not necessarily a problem: I gives us more leeway to nail down something sane (if we want to).

**Comment by goessner** [comment]
... with JavaScript ...
```js
const o = {};
o.a === o.b;  // true
```
due to ` undefined === undefined`.

**Comment by danielaparker** [comment]
> I've extended the query which compares two paths via equals to include absent keys: https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_equals_with_path_and_path.html. No consensus, not even a majority at this point.

Isolating the empty key behavior, I think the results are consistent with what we understand about the implementations. By my count, 12 implementations select the `{}` item. It depends on whether the implementation returns a value (such as `undefined`) for an absent key, or whether it handles it as a recoverable error. The Javascript ones that return `undefined` for an absent key select `{}`, as would be expected. Jayway, which handles an absent key as a recoverable error that takes out the term, does not select `{}`, again as expected.     

None select `{"key1": null}` or `{"key2": null}`. I think it would be interesting to add `{"key1": false}` to the document.

**Comment by cburgmer** [comment]
> I think it would be interesting to add {"key1": false} to the document.

Done :)

**Comment by gregsdennis** [comment]
I would like to add here, just to ensure that it's documented, that C# recently added `x is {}` as an expression equivalent to `x != null`.

Therefore returning `{}` could be quite confusing for some users.

**Comment by danielaparker** [comment]
> > I think it would be interesting to add {"key1": false} to the document.
> 
> Done :)

Okay, from the data (checked cells correspond to selected values), it appears that twelve implementations consider absent is equal to absent, while one, PHP (galbar-jsonpath), considers absent is equal to false but not to absent.

The ones that consider absent is equal to absent do so for different reasons. Cpp (jsoncons) and dotNET (JsonCons.JsonPath)
evaluate absent to be `null`, and `null` is equal to `null`. The JavaScript implementations evaluate absent to be `undefined`,
and `undefined`  is equal to `undefined`.

Implementation              |{}         |{"key1" : null}|{"key2" : null}|{"key1" : false}|{"key2" : false}|
----------------------------|-----------|---------------|---------------|----------------|----------------|
Clojure (json-path)         |<em>&#x2713;</em>|<em>&#x2713;</em>|<em>&#x2713;</em>|&nbsp;|<em>&#x2713;</em>|
Cpp (jsoncons)              |<em>&#x2713;</em>|<em>&#x2713;</em>|<em>&#x2713;</em>|&nbsp;|&nbsp;|
dotNET (JsonCons.JsonPath)  |<em>&#x2713;</em>|<em>&#x2713;</em>|<em>&#x2713;</em>|&nbsp;|&nbsp;|
dotNET (JsonPathLib)        |<em>&#x2713;</em>|&nbsp;|&nbsp;|&nbsp;|&nbsp;|
dotNET (Manatee.Json)       |<em>&#x2713;</em>|&nbsp;|&nbsp;|&nbsp;|&nbsp;|
Elixir (warpath)            |<em>&#x2713;</em>|<em>&#x2713;</em>|<em>&#x2713;</em>|&nbsp;|&nbsp;|
Erlang (ejsonpath)          |<em>&#x2713;</em>|&nbsp;|&nbsp;|&nbsp;|&nbsp;|
JavaScript (brunerd)        |<em>&#x2713;</em>|&nbsp;|&nbsp;|&nbsp;|&nbsp;|
JavaScript (Goessner)       |<em>&#x2713;</em>|<em>&#x2713;</em>|<em>&#x2713;</em>|&nbsp;|&nbsp;|
JavaScript (jsonpath)       |<em>&#x2713;</em>|<em>&#x2713;</em>|<em>&#x2713;</em>|&nbsp;|&nbsp;|
JavaScript (jsonpath-plus)  |<em>&#x2713;</em>|<em>&#x2713;</em>|<em>&#x2713;</em>|&nbsp;|&nbsp;|
Ruby (jsonpath)             |<em>&#x2713;</em>|<em>&#x2713;</em>|<em>&#x2713;</em>|<em>&#x2713;</em>|<em>&#x2713;</em>|
PHP (galbar-jsonpath)       |&nbsp;|&nbsp;|&nbsp;|<em>&#x2713;</em>|<em>&#x2713;</em>|

**Comment by cabo** [comment]
112 minutes:

> Tim: So you'd like `undefined` behaviour?
> 
> Carsten: Yes, but it seems that others like `NaN` better
> 
> Carsten: Whatever we decide, we can always write an existence test that
> inverts, my feeling `undefined` is the right feeling
> 
> Tim: Should we have a use case contest on this?
> 
> **Action**: Discuss the use cases of this on the mailing list

So we need to discuss this.

**Comment by danielaparker** [comment]
> 112 minutes:
> 
> > Tim: So you'd like `undefined` behaviour?
> > Carsten: Yes, but it seems that others like `NaN` better

By `NaN`, do you mean literally an IEEE 754 `NaN`, to have `<absent>` evaluate to that? First, I don't think any existing JsonPath implementation does that. Second, not all mainstream programming languages require IEEE 754 or `NaN`.

Generally speaking, notions such as `undefined` or `null` tend to be language specific. Some languages support `undefined` as a primitive value for when a variable is declared but not initialized, some support something similar for `null`, some want to make it impossible or to have a variable that is not initialized.

There are alternatives, It isn't necessary to have `<absent>` evaluate to a "value", whether `NaN`, `undefined` or `null`. `<absent>` can be considered an error, resulting in the term in question being unmatched. That's the approach of JAVA Jayway, and the implementations that followed Jayway.

**Comment by cabo** [comment]
> On 24. Jan 2022, at 01:59, Daniel Parker ***@***.***> wrote:
> 
> 
> 112 minutes:
> 
> Tim: So you'd like undefined behaviour?
> Carsten: Yes, but it seems that others like NaN better
> 
> By NaN, do you mean literally an IEEE 754 NaN, to have <absent> evaluate to that?

NaN is just a placeholder for a value representing “absent" that behaves like NaN:  It does not compare equal to anything, including itself.
This obviously is a weird value to have, and I believe it was introduced in IEEE 754 as a hack to make it safer to reuse existing code with that new standard, not because having such a value is such a great concept.

> First, I don't think any existing JsonPath implementation does that. Second, not all mainstream programming languages require IEEE 754 or NaN.

Right.  But that is not relevant to the discussion at hand.

> Generally speaking, notions such as undefined or null tend to be language specific. Some languages support undefined as a primitive value for when a variable is declared but not initialized, some support something similar for null, some want to make it impossible or to have a variable that is not initialized.

“Undefined” again is a placeholder for any non-JSON value representing “absent" that *does* compare equal to itself.

> There are alternatives, It isn't necessary to have <absent> evaluate to a "value", whether NaN, undefined or null. <absent> can be considered an error, resulting in the term in question being unmatched. That's the approach of JAVA Jayway, and the implementations that followed Jayway.

***@***.*** == @.b` should have the opposite value to ***@***.*** != @.b`.
This is hard to do with throwing an exception.
There is nothing wrong with a value representing “absent”.
“undefined” and “NaN” were just figures of speech for values representing “absent” that do or do not compare equal to themselves.

Grüße, Carsten

**Comment by danielaparker** [comment]
> On 24. Jan 2022, at 01:59, Daniel Parker ***@***.***> wrote: 112 minutes: Tim: So you'd like undefined behaviour? Carsten: Yes, but it seems that others like NaN better By NaN, do you mean literally an IEEE 754 NaN, to have <absent> evaluate to that?
> NaN is just a placeholder for a value representing “absent" that behaves like NaN: It does not compare equal to anything, including itself. 

Thanks for clarifying. Like SQL NULL then.

> There are alternatives, It isn't necessary to have <absent> evaluate to a "value", whether NaN, undefined or null. <absent> can be considered an error, resulting in the term in question being unmatched. That's the approach of JAVA Jayway, and the implementations that followed Jayway.
> ***@***.*** == @.b` should have the opposite value to ***@***.*** != @.b`. 

Do you think so? Personally, I would be fine if
```
{"c" : 1}

$[?(@.b == @.b)]
$[?(@.b != @.b)]
```
both resulted in no results (although Jayway does not.)

> There is nothing wrong with a value representing “absent”. 

It's unnatural in some programming languages. A more universal notion is optionality, a result that may or may not have a value.

Daniel

**Comment by danielaparker** [comment]
> ... with JavaScript ...
> 
> ```js
> const o = {};
> o.a === o.b;  // true
> ```
> 
> due to ` undefined === undefined`.

Note that by introducing `undefined` as a value to represent absent, you've effectively extended the JSONPath type system to be more than JSON, JSON does not have the notion of `undefined`. In JavaScript JSONPath implementations, you can write `$..[?(@.<absent> == undefined)]` (returns everything) and `$..[?(@.<absent> != undefined)]` (returns nothing), do you plan to support that notation as well? Or do you plan to only allow the construction of `undefined` indirectly as the result of evaluating `@.<absent>`? Regardless, you've still introduced a non-JSON type. What happens in a future version of JSONPath that supports functions of expressions, like all the current JavaScript ones? Do they accept `undefined` as an argument, like JavaScript? More things to reason about.

Of course, there is plenty of prior experience that bears on these matters. JMESPath stays entirely within the JSON type system as a design principle, and represents the result of `@.<absent>` as a JSON null value. A couple of JSONPath implementations (a distinct minority) also take that approach. JSONPath implementations that use a scripting language having `undefined` as a primitive type usually use `undefined` for absent. The most important implementations that implement their own expression language, notably Jayway, handle absent as a recoverable error. 



```

**Comment by gregsdennis** [comment]
> Note that by introducing `undefined` as a value to represent absent, you've effectively extended the JSONPath type system to be more than JSON, JSON does not have the notion of `undefined`.

JSON doesn't have `undefined`, but it does have a distinction between `null` and absent, which is what `undefined` represents.  It doesn't need to be a "value" that's recognized externally; we intend it as an internal placeholder that indicates the absence.  The question we're raising here is, internally to an implementation, how the absence of one property equate to the absence of another property?

> you can write `$..[?(@.<absent> == undefined)]` ...

This will not be a supported syntax in JSON Path.  Instead we are using implicit existence: `$..[?(@.foo]` for presence test and `$..[?(!@.foo)]` for absence test.

**Comment by cabo** [comment]
> > due to ` undefined === undefined`.
> 
> Note that by introducing `undefined` as a value to represent absent, 

We don't have a PR for this issue yet, but I don't think we need to introduce `undefined` in the specification.
This is just a figure of speech to have an reasonable conversation about this issue.

> you've effectively extended the JSONPath type system to be more than JSON, 

Yes.
This is good.

> JSON does not have the notion of `undefined`. In JavaScript JSONPath implementations, you can write `$..[?(@.<absent> == undefined)]` (returns everything) and `$..[?(@.<absent> != undefined)]` (returns nothing), do you plan to support that notation as well? Or do you plan to only allow the construction of an `undefined` indirectly as the result of evaluating `@.<absent>`? 

I don't see a point in providing a literal notation for the absent condition.

> Regardless, you've still introduced a non-JSON type. What happens in a future version of JSONPath that supports functions of expressions, like all the current JavaScript ones? Do they accept `undefined` as an argument, like JavaScript? More things to reason about.

I would expect so.

> Of course, there is plenty of prior experience that bears on these matters. JMESPath stays entirely within the JSON type system as a design principle, and represents the result of `@.<absent>` as a JSON null value. 

In my eyes, that would be a bug; a null value is different from absence.

> [...] The most important and widely used implementations that implement their own expression language, notably Jayway, handle absent as a recoverable error affecting that term.

Curious: Where are these throws caught ("recoverable")?
So far, we have been able to avoid throw/catch, and I wouldn't mind if it stayed that way.

**Comment by glyn** [comment]
Thinking further on whether `@.doesnotexist` needs to have a value or not, would we also expect the following to be true?
```
@.doesnotexist[0] != @.alsodoesnotexist[0]
```

**Comment by cabo** [comment]
> Thinking further on whether `@.doesnotexist` needs to have a value or not, would we also expect the following to be true?
> 
> ```
> @.doesnotexist[0] != @.alsodoesnotexist[0]
> ```

Both don't exist, so they are equal, so they are the same, so no.

**Comment by glyn** [comment]
Argh! I meant would we also expect that expression to be false.

But my point here is that the undefined value is acting more than a figure of speech here because when we apply selectors to it (such as [0]), it is preserved. I'm not sure how we could explain that propagation behaviour without there being an undefined value of some sort, even though it may be implicit. Of course, a clean way of defining this would be to say that each selector produces an optional nodelist with an "absent" nodelist which is preserved by other selectors. As was pointed out earlier, we don't need to have an explicit representation for the "absent" nodelist, but we do need to talk about how the "absent" nodelist behaves.

Does this help?

**Comment by cabo** [comment]
Yes, that (empty input ➔ empty output) is part of the definition of the path selectors, and maybe needs to be made more explicit there.  It is not an aspect of the filter expression language.

**Comment by danielaparker** [comment]
> > Note that by introducing `undefined` as a value to represent absent, you've effectively extended the JSONPath type system to be more than JSON, JSON does not have the notion of `undefined`.
> 
> JSON doesn't have `undefined`, but it does have a distinction between `null` and absent, which is what `undefined` represents. It doesn't need to be a "value" that's recognized externally; we intend it as an internal placeholder that indicates the absence. The question we're raising here is, internally to an implementation, how the absence of one property equate to the absence of another property?
> 
That isn't my understanding of `undefined`, my understanding is from Javascript, where `undefined type` is a primitive type that has one value `undefined`.

Your understanding seems to be closer to c++ `std::optional`, rust std::option, or c# `?`. Something with `HasValue` and `Value` properties, considered abstractly. From a conceptual point of view, I think that's better, because it's less Javascriptish, not many consider Javascript to be a great design, and all values remain JSON. 

 Daniel

**Comment by danielaparker** [comment]
> > Of course, there is plenty of prior experience that bears on these matters. JMESPath stays entirely within the JSON type system as a design principle, and represents the result of `@.<absent>` as a JSON null value.
> 
> In my eyes, that would be a bug; a null value is different from absence.
> 
It's all a matter of convention, which varies across languages. In Javascript, `map[<absent>]` returns `undefined`; in Java, `map.get(<absent>)` returns `null`, in C++, `map[<absent>]` returns a default constructible type, in C#, `dictionary[<absent>]` throws. 

The nice thing about the JMESPath convention is that it leads to a simple consistent model that stays entirely within the JSON type system. Regarding how this corresponds to user intuition, of all the JMESPath issue logs and all the JMESPath discussions that I've followed, I've never seen this come up. But I think the same can be said of other conventions. Users care about many things, but they don't care about this, whatever the convention is, they figure it out and move on.  

Daniel

**Comment by danielaparker** [comment]
> > Thinking further on whether `@.doesnotexist` needs to have a value or not, would we also expect the following to be true?
> > ```
> > @.doesnotexist[0] != @.alsodoesnotexist[0]
> > ```
> 
> Both don't exist, so they are equal, so they are the same, so no.

In Javascript, that would result in an exception being thrown, with message "Cannot read properties of undefined"

**Comment by cabo** [comment]
On 26. Jan 2022, at 01:49, Daniel Parker ***@***.***> wrote:
> 
> 
> Thinking further on whether @.doesnotexist needs to have a value or not, would we also expect the following to be true?
> 
> @.doesnotexist[0] != @.alsodoesnotexist[0]
> 
> Both don't exist, so they are equal, so they are the same, so no.
> 
> In Javascript, that would result in an exception being thrown, with message "Cannot read properties of undefined”

But this is not JavaScript.

From context, this seems to be meant as a part of a filter expressions.

LHS and RHS of `!=` are two path constructs.  
These don’t have any values but nodelists; so I don’t know where `undefined` (or any other surrogate for absent) comes in.  
The results of these two paths then are used in a comparison, which causes the JSON value at the node selected by each path is obtained.  
This is where this concept of `undefined` (absent) comes in, because the nodelists are empty, and therefore there is no such JSON value, so we need to remember that the input to the comparison is something else.

Grüße, Carsten

**Comment by danielaparker** [comment]
> On 26. Jan 2022, at 01:49, Daniel Parker ***@***.***> wrote: Thinking further on whether @.doesnotexist needs to have a value or not, would we also expect the following to be true? @.doesnotexist[0] != @.alsodoesnotexist[0] Both don't exist, so they are equal, so they are the same, so no. In Javascript, that would result in an exception being thrown, with message "Cannot read properties of undefined”
> But this is not JavaScript. From context, this seems to be meant as a part of a filter expressions. LHS and RHS of `!=` are two path constructs. These don’t have any values but nodelists; 

In most prior experience that I know of in JSONPath implementations, the LHS and RHS in filter expressions are expressions that evaluate to single values (null, true, false, string, number, array, object and in some cases undefined), not result lists. These JSONPath implementations group largely into two categories,

- Implementations that use Javascript/Python/Lua to evaluate filter expressions, where the symbol `@` in the script is substituted with the current node value, and `@.expr` is evaluated as a Javascript/Python/Lua variable
- Implementations that evaluate `@.<expr>` as a JSONPath expression, but using rules so that the result is produced as a single value rather than a result list. Jayway JSONPath is an example, when evaluating `@.<expr>` in a filter, the slice, union and filter selectors will always produce results wrapped in an array, the wildcard selector will produce results wrapped in an array if there are more than two items, the identifier and index selectors will produce a single value if matched, otherwise a null .  

Between the Javascript/Python implementations and Java Jayway , that accounts for most of the JSONPath implementations in use. Do you know of any prior experience where the LHS and RHS in filter expressions evaluate to result lists (node lists)?

Thanks,
Daniel

**Comment by goessner** [comment]
In JavaScript ...

```js
const o = {}
o.doesnotexist != o.alsodoesnotexist              // undefined != undefined ... false
o.doesnotexist?.[0] != o.alsodoesnotexist?.[0]    // undefined != undefined ... false
```

... with new *optional chaining*

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

**Comment by cabo** [comment]
> In most prior experience that I know of in JSONPath implementations, 

I wasn't talking about implementations, but about the processing model we have adopted.

**Comment by danielaparker** [comment]
> > In most prior experience that I know of in JSONPath implementations,
> 
> I wasn't talking about implementations, but about the processing model we have adopted.

Interesting.

So, given
```
[{"foo":"bar"}]

$[?(@.foo == 'bar')]
```

If `@.foo` resolves to a "result list", `['bar']`, how is the result list containing `bar` compared to the single value `bar`? What convention are you following to support comparison between a "result list" and a single value. I apologize if I missed that in the draft.

In all the prior experience that I'm familiar with, `@.foo` always evaluates to a single value according to rules. That's true of both implementations that treat `@` as a Javascript like variable, much in fact like it is in the draft,

```
rel-path     = "@" *(S (dot-selector / index-selector))
```
and in implementations where the grammar of `@.<expr>` is the same as `$.<expr>`. (For these implementations, `@.<expr>` is always evaluated to a single value following rules that may differ from evaluating `$.<expr>` to a result list.)

So your approach sounds like something different.

Thanks,
Daniel

**Comment by timbray** [comment]
We have rough consensus that absent does equal absent. Tagged as editorial.
