### ISSUE TITLE
Re-open issues labeled with "revisit-after-base-done" after IESG submission of base document

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#151]
This approach was agreed at the [January 2022 interim WG meeting](https://datatracker.ietf.org/meeting/interim-2022-jsonpath-01/materials/minutes-interim-2022-jsonpath-01-202201181100-00).

[These](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues?q=is%3Aissue+is%3Aclosed+label%3Arevisit-after-base-done) are those issues.

**Comment by glyn** [comment]
Re-opened all the issues labelled revisit-after-base-done. I hesitate to remove the label in case someone thinks this is premature and we need to close them all again for a while...

**Comment by cabo** [comment]
Yes, please leave the labels on, in case someone misunderstands these as issues on the base spec.

We haven't really discussed how to organize any work on future additions to jsonpath; we'll not have an active IETF WG during the time we figure out what we actually want to propose, but we could still use the mailing list of the dormant WG.  It is also not clear that extension proposals will lead to reactivating the WG, they *could* happen in other WGs, or simply not happen at all.  So I think what should happen now is that we, in due time, develop any formative contributions that we'll want to have, with a view to having the combination of the various extensions act as a second wave once we have something we like.  But that will be a different kind of work than the work in the active WG that led to JSONPath-base.

**Comment by gregsdennis** [comment]
FWIW, I'm happy to continue using my library as a test bed for new behaviors, behind configuration, of course.

**Comment by gregsdennis** [comment]
Also, I think for some of the newly re-opened issues, it may benefit us to close them and open new issues with summaries of the discussion.
