### ISSUE TITLE
.length needs to be addressed

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#154]
Ref: https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/153#issuecomment-1027657135

The original post shows examples of a `.length` syntax that allows the user to get the number of elements in an array.  This was primarily used in the `[(<expr>)]` syntax such as `[(@.length-1)]` as a way to denote the last element in an array.  For now, we have elected to exclude this syntax.

The `.length` syntax can also be used in the `[?(<expr>)]` syntax such as `[?(@.length<10)]` to find array elements which are objects or arrays which themselves have fewer than 10 keys/items.

However, there is an ambiguity between `length` as a property of an array and `length` as an object key.  **We need to address this ambiguity.**

As of opening this issue, the syntax is disallowed, implying it can only have the "object key" semantics.  But since the vast majority of implementation support this ([object](https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_key_named_length.html) / [array](https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_key_named_length_on_array.html)), it can be inferred that path authors use this feature.  Therefore, we need to support this feature in some way.

Due to the ambiguity stated above, I think we need an alternate syntax.  To start, I would like to propose the function syntax `length(@)` which would return the number of items in an object/array or 0 for non-structured values.

It is recognized that we don't yet have a function syntax defined, so maybe that needs to be addressed first.  I'm also open to other proposals that wouldn't require that we define a new class of syntax.

**Comment by nichtich** [comment]
How about a plain keyword? 

`$..[?length > 0]` get all non-empty arrays (and objects?)

**Comment by gregsdennis** [comment]
Thanks for the idea, but just the keyword doesn't show for applying the function to nested values.  For example, you couldn't do this: `$[?(@.foo[6].length > 10)]` which is something many implementations support today.

A function syntax could handle it though: `$[?(length(@.foo[6]) > 10)]`.

**Comment by gregsdennis** [comment]
> `$[? @.foo[6][?length>10] ]` or `$ ?(@.foo[6] ?(length>10) )`

That's a lot of additional syntax that would have to be supported.

> `$.length` - size or property length, depending on context

This is the problem that we're trying to address with this issue.  How do you specify that you want length of there is a `length` property?

**Comment by nichtich** [comment]
> `$.length` - size or property length, depending on context
> This is the problem that we're trying to address with this issue. How do you specify that you want length of there is a length property?

As far as I understand `.length` returns the `length` property on JSON objects and the array size on JSON arrays.

* https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_key_named_length.html
* https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_key_named_length_on_array.html

Or drop support of `.length` on arrays. Either way some current implementations will not conform to the upcoming specification.

> That's a lot of additional syntax that would have to be supported.

I think the question of this issue is 

1. whether ​to support existing implementations that allow `.length` on arrays or support existing implementations that don't allow `.length` on arrays, 
2. whether to add some other feature to get array length

**Comment by gregsdennis** [comment]
> As far as I understand .length returns the length property on JSON objects and the array size on JSON arrays. - @nichtich 

It does this historically because @goessner's implementation did this.  His implementation use the inherent Javascript and PHP meanings behind the syntax.  But this spec effort is striving for language agnosticity, which means we can't rely on that syntax.  We need something more well-defined that works interoperably.

The question at hand is as I stated it in the opening comment:

> Due to the ambiguity stated above, I think we need an alternate syntax.

This is akin to your # 2.  I think we have already decided fairly unilaterally that we will not be supporting `.length` due to the ambiguity it presents.

**Comment by nichtich** [comment]
@gregsdennis wrote:

> I think we have already decided fairly unilaterally that we will not be supporting `.length` due to the ambiguity it presents

Then this issue can be closed. Whether and how to support other methods to access and/or filter (by) number of elements would be an additional feature request.

**Comment by cabo** [comment]
I'm not sure what was unilateral about this decision, and we haven't confirmed it on the mailing list, but I agree that `.length` would be an odd addition to the current draft.

What we haven't decided is whether there should be ways to find out information about a JSON value being looked at, such as the length of the string, the size of an array, or the number of pairs in a JSON object.

**Comment by gregsdennis** [comment]
This issue can't be closed yet, for the reason @cabo suggested: we should still support the _functionality_, but the syntax will be different.

**Comment by glyn** [comment]
This was addressed as part of the function extension point work.
