### ISSUE TITLE
Normalized Paths and normalization

### ISSUE THREAD

**Issue by benkehoe** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#155]
The [current definition for Normalized Paths](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/blob/ca83d54f420576b03d0700e201c5447a2b96aa0b/draft-ietf-jsonpath-base.md#normalized-paths) is a separate grammar that happens to be a subset of the general path grammar. Would it make sense to make it more directly a subset (e.g., as a set of constraints on selectors), which could then include a "normalization" operation that takes a standard path and returns a Normalized Path or an error if it cannot be normalized?

A use case: if I am a developer intending to provide an interface that accepts a JSON Path that must refer to a single element, is it reasonable for me to expect that a user of that interface knows what Normalized Paths are such that I can require a Normalized Path (for example, they know they must use single quotes, not double quotes), or would it be better to allow them to specify a standard path and then attempt to normalize it as part of input validation?

**Comment by gregsdennis** [comment]
Speaking as another developer, I think you'll want to support translation to normalized paths.  Most people will want to write the dot syntax if they can. So long as they specify a single node, your code should work.

I don't think it's a matter of what we suggest rather than one of usability for your consumers.

**Comment by glyn** [comment]
> The [current definition for Normalized Paths](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/blob/ca83d54f420576b03d0700e201c5447a2b96aa0b/draft-ietf-jsonpath-base.md#normalized-paths) is a separate grammar that happens to be a subset of the general path grammar.

`normalized-path` is indeed a subset of `json-path`. The ABNF was written to make sure this is true and the spec says so: "A Normalized Path is a JSONPath with restricted syntax that [...]".

> Would it make sense to make it more directly a subset (e.g., as a set of constraints on selectors), which could then include a "normalization" operation that takes a standard path and returns a Normalized Path or an error if it cannot be normalized?

I don't think ABNF has any way of defining a rule which is expressed as a constrained form of another rule. Implementations are free to do this if they can and are also free to provide a "normalize()" operation.

**Comment by cabo** [comment]
> 
> I don't think ABNF has any way of defining a rule which is expressed as a constrained form of another rule. Implementations are free to do this if they can and are also free to provide a "normalize()" operation.

Right, ABNF is a grammar, not a transformation language.
I think we are best off with making sure there indeed is a transformation that always works.
But we can describe that in English.

**Comment by benkehoe** [comment]
>  The ABNF was written to make sure this is true and the spec says so: "A Normalized Path is a JSONPath with restricted syntax that [...]".

I agree, but what I'm saying is, defining it as its own complete ABNF syntax does not provide a straightforward path to an implementation providing normalization. I'm asking if it would make sense to merely define Normalized Paths as:
> normalized-path           = root-selector *(normal-index-selector)

And then have Normal Index Selector defined alongside the other selectors, and for Dot Selector and Index Selector, define the operation to transform them into a Normal Index Selector, in terms of the corresponding components of their ABNF definitions. For example, the operation to transform `single-quoted` in Index Selector into `normal-single-quoted` in Normal Index Selector.

**Comment by glyn** [comment]
Implementations are already free to structure themselves along the lines
you suggest without needing the spec to be changed. What more needs to be
said in the spec?

**Comment by benkehoe** [comment]
Two reasons: first, defining normalization in the spec would encourage implementations to provide that (useful) functionality (personally, I'd even say "implementations SHOULD provide normalization" would be worth including), and second, it would ensure that implementations of normalization are both complete and identical.

**Comment by goessner** [comment]
Hello Ben,

now I finally understand your argumentation.

I like that! Thus third party applications, while reusing any 
spec-conforming jsonPath engine, can be sure to be understood, when 
feeding normalized pathes into them or asking normalized pathes from them.
--
sg


Am 16.02.2022 um 17:47 schrieb Ben Kehoe:

**Comment by gregsdennis** [comment]
I'm still missing something.

The spec already defines what a normalized path is.  This means that implementations need to support them, thereby ensuring that applications can rely on them.  All of this is already in place.

How does changing the ANBF alter/improve usability of an implementation?

**Comment by glyn** [comment]
On Wed, 16 Feb 2022, 23:25 Greg Dennis, ***@***.***> wrote:

> I'm still missing something.
>
> The spec already defines what a normalized path is. This means that
> implementations need to support them, thereby ensuring that applications
> can rely on them. All of this is already in place.
>

There is no requirement in the current spec that implementations support
normalized paths.

An implementation may output normalized paths instead of, or in addition
to, the values identified by those paths, but if it doesn't, the
implementation need have no support for normalized paths.

> How does changing the ANBF alter/improve usability of an implementation?
>

It doesn't. But if the spec required implementations to support a
normalisation function, that could improve usability. But I'm not sure we
want to go mandating the content of application APIs. Maybe someone else
who has grasped what is being proposed could clarify?

**Comment by benkehoe** [comment]
1. Normalized Paths are presented separately, and only mentioned by the rest of the spec in terms of being the result of a query. Nowhere in the spec is the idea of normalization—turning a standard path into normalized path—even mentioned, let alone recommended or required. This makes it less likely that implementations will support such an operation.
2. The syntax of normalized paths is presented completely separately from standard paths. It's stated (and guaranteed) that it's a subset of standard path syntax, but no further details on the relationship are presented. If an implementation wants to provide normalization, it is up to the developer to delve into the syntax and determine how normalization actually works, increasing the likelihood of bugs and inconsistencies across implementations. The differences in escaping rules are ripe for this.

What I'm asking is for the spec to define normalization and its semantics, and detail the normalization procedure to reduce the likelihood of implementation bugs. Potentially recommend that implementations SHOULD provide normalization.

**Comment by danielaparker** [comment]
> I'm asking if it would make sense to merely define Normalized Paths as:
> 
> > normalized-path           = root-selector *(normal-index-selector)
> 

Agreed. Clarity is a good thing, and ABNF is clearer than English when defining syntax.

> And then have Normal Index Selector defined alongside the other selectors, and for Dot Selector and Index Selector, define the operation to transform them into a Normal Index Selector, in terms of the corresponding components of their ABNF definitions. For example, the operation to transform `single-quoted` in Index Selector into `normal-single-quoted` in Normal Index Selector.

Having authored a couple of implementations that support normalized paths, and studied a few others, I don't see a need for this. When an implementation produces normalized paths, it simply produces them from indices and names as they process a query against a JSON document, there's no converting `single quoted` into `normal quoted`. And when an implementation consumes a normalized path, from the implementation's perspective, they're no different from any other path. The user knows they're going to get one value back, the implementation doesn't need to know that. 

Most existing implementations that support normalized paths have a single "query" function that accepts any path, normalized or not. The exceptions are the ones that return normalized paths in a more structured form, e.g. as `List<NormalizedPath>`, and provide a function that can query using a `NormalizedPath` argument.

**Comment by danielaparker** [comment]
> > And when an implementation consumes a normalized path, from the implementation's perspective, they're no different from any other path. The user knows they're going to get one value back, the implementation doesn't need to know that.
> 
> This isn't true when a system using a JSON Path implementation is receiving the path from an outside source, it then _doesn't_ know that it will get one value back; it needs some way of determining whether that will happen or not. This is exactly the situation in [Amazon States Language](https://states-language.net/#ref-paths). 

Okay, fair enough. 

> 3. Accept any path and determine whether that path will always return one value, rejecting the path if it does not. This would be easily done by attempting to normalize the path. Without normalization, the system is left to perform some sort of ad hoc introspection-based normalization that the developer would have to come up with on their own.
> 
But you can't compute normalized paths without the document, if the input path contains certain kinds of selectors, such as the 
wildcard or the recursion selectors. And if you say you're going to reject paths that have such selectors, than you may as well just take Amazon's approach, and reject paths that have selectors other than ones that will only ever return at most one value.

**Comment by gregsdennis** [comment]
> But you can't compute normalized paths without the document - @danielaparker 

You can absolutely do this. A path should be completely independent of any document.  You should be able to apply a given path to any document.

I would say that a normalized path is one that produces at most one value **regardless** of the document it's applied to, presented in a specified format, e.g. `$['foo'][1]['bar']`.  Some paths cannot be normalized because, for some documents, they would return multiple values, e.g. `$..foo`.  That some paths cannot be normalized is one of the reasons we've defined normalization to begin with.

Can you contrive a path that guarantees returning a single value that cannot be normalized without a document?

**Comment by benkehoe** [comment]
Negative array indexes are one case where they will return at most one node, but cannot be normalized without a document.

**Comment by benkehoe** [comment]
In which case, maybe what I'm asking for is an operation that takes a path and returns a boolean whether it is guaranteed to return at most one value. I thought normalization provided that functionality, and I still think it's useful, but maybe defining such a check on standard paths is the way? It could even be required without requiring implementations to support normalized paths.

**Comment by danielaparker** [comment]
> Can you contrive a path that guarantees returning a single value that cannot be normalized without a document?

That's not the problem that @[benkehoe](https://github.com/benkehoe) posed. Rather, the problem they posed is

> 3. Accept any path and determine whether that path will always return one value, rejecting the path if it does not. This would be easily done by attempting to normalize the path. 

Consider the path (it can be any path) "$..foo". We can't know whether that path corresponds to a single normalized path without applying it to a document (obviously.) It might. It might not. It depends on the document.

Moreover, we have no way of knowing if any path (except for trivial paths like "$" or "$[?(true)]") will "always return one value".  It may return no value. 

Amazon's approach with "reference paths" is to accept only paths restricted to selectors that are guaranteed to return at most one value. That would be the root selector, the index selector, and the identifier selector. That's easy enough to check, parse the input path, and see if that emits any other kind of selector, if so, reject. I wouldn't call that "attempting to normalize the path".

**Comment by benkehoe** [comment]
I did say "return one value", but I meant "at most one value", as of course a document may not contain a value for a given path.

It still seems like defining an operation for this check that implementations SHOULD or MUST provide would be useful, as it directly provides the desired information rather than relying on introspection of the selectors that the implementation may or may not provide.

**Comment by cabo** [comment]
On 18. Feb 2022, at 01:32, Ben Kehoe ***@***.***> wrote:
> 
> Negative array indexes are one case where they will return at most one node, but cannot be normalized without a document
> 


There is no concept of “normalization” in the draft right now, only normalized Paths.
You get normalized Paths by executing a query against a document, and if the implementation supports outputting both values and location for each result node, the latter give you a bunch of normalized paths.

It seems to me you want to define an abstract operation where a query is executed without a document at hand, and if the query is unambiguous without that, you take the normalized path and consider that process "Normalization”?

A nice feature an implementation can provide, but probably not worth defining in the standard, because you can easily build it from query execution as described.

Grüße, Carsten

**Comment by benkehoe** [comment]
> you can easily build it from query execution as described.

> if you say you're going to reject paths that have such selectors, [...] reject paths that have selectors other than ones that will only ever return at most one value, regardless of the document.

I'm concerned these responses muddle the difference between an implementer of the spec and a user of such an implementation. If I'm building an application like the Amazon example, where I need to validate that an input path will return at most one node, I am not going to go to the spec, build a parser, and build in the logic myself to determine that. I'm going to look for an implementation. To be spec-compliant, an implementation has to provide me with a `query` operation that takes a document and returns a nodelist, in whatever form it chooses. It does *not* have to provide me with a representation of the parsed path that I could use to inspect the selectors. It does *not* have to allow me to execute a query without a document. It does *not* have to support normalized paths. What I'm saying is, there are applications that have the need to validate that a path will return at most one value; defining that operation in the spec to encourage (or even require) implementations to provide that operation, would be of benefit to users of implementations.

**Comment by danielaparker** [comment]
> Negative array indexes are one case where they will return at most one node, but cannot be normalized without a document.

Interesting observation. Negative array indexes make sense in Amazon reference paths, it makes sense to use -1 to refer to the last element in an array. I think reference paths and normalized paths are just different concepts.

**Comment by gregsdennis** [comment]
> Negative array indexes are one case where they will return at most one node, but cannot be normalized without a document.

I wouldn't consider negative indices to be part of the normalized syntax.  While it does only identify a single element, that isn't the only requirement of a normalized path.

**Comment by benkehoe** [comment]
Ok, given that normalized paths do not suffice for the reference path use case, I think this is what I'm proposing:

* Define a *reference selector* as a selector that returns at most one node.
* Annotate the root selector, dot selector, and index selector as being reference selectors.
* Define a *reference path* to be a path consisting only of reference selectors.
* Recommend or require that implementations support an `is_reference_path` operation that checks if a path is a reference path or not.

**Comment by gregsdennis** [comment]
I'm not so sure that this is something that JSON Path needs to define or recommend.  It seems like more of an application-level requirement.

**Comment by benkehoe** [comment]
If applications were expected to do their own JSON Path parsing, I'd agree, but I'm saying it'd be useful to standardize the concept for libraries to provide to applications, rather than leave it to be ad hoc and inconsistent.

Put another way, if I'm developing an application and need reference path inputs, and the available JSON Path libraries don't provide support, I'm faced with either writing my own implementation or going with an alternative language like JSON Pointer (note that the Amazon example has inputs that must be reference paths and ones that can be free-form, it would have to use different syntax for different fields). Is that an acceptable situation to put developers in?

**Comment by gregsdennis** [comment]
Speaking as a package owner, I'd say that it's the responsibility of the package owner to understand the needs of their consumers and provide such support.

I do similarly for other specs, like JSON Schema (I'm on that spec team also). A lot of extra functionality is not defined in the spec and is left to implementors to decide how best to meet the needs of their slice of economy.

I find that implementors who want their packages to be used are quite responsive to requests like this.

As a feature finds common footing across implementations, the WG can then look at incorporating such functionality into either the spec or accompanying documentation/guidance.  But until then, it's an external concern.

**Comment by gregsdennis** [comment]
To be clear, I think it's valid for the spec to define (and name) a kind of path that can identify at most a single node regardless of the document that it is given.  (I thought that's what "normalized path" was, but it seems I'm mistaken.)

I _don't_ think it's valid for the spec to provide guidance that implementions should support conversions from a standard path to this "singular" form.

**Comment by benkehoe** [comment]
The thing you think is valid is the first three bullets from [my revised request above](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/155#issuecomment-1046326449):
* Define a *reference selector* as a selector that returns at most one node.
* Annotate the root selector, dot selector, and index selector as being reference selectors.
* Define a *reference path* to be a path consisting only of reference selectors.

The thing you don't think is valid is slightly different from the fourth bullet, which is not a conversion but an evaluation whether a standard path meets the above definition or not. Even so whether this guidance is in the spec or not is still separable from the above definition being included.
* Recommend or require that implementations support an `is_reference_path` operation that checks if a path is a reference path or not.

**Comment by gregsdennis** [comment]
> Define a reference selector...

I think you have some terminology mixed.  A "selector" is `.foo`, `['foo']`, `[1]`, etc.  Each instance is a selector.  The normalized path specifically uses only `['foo']` and `[1]` (and `$`, but that's not debated).

Are you suggesting that we create another selector?

 I'm not sure what the motivation is behind the other two points. How does this help you achieve your goal of having a party that references a single node?

---

I understand that you're asking for this because some applications require single-node paths as input, but perhaps they're just using the wrong model.  Maybe they should be using JSON Pointer instead.

We've declared that we're not in competition with JSON Pointer, noting how is designed for a different purpose.

I'm just wondering if the question stems from a poor design choice by some third party.

**Comment by cabo** [comment]
On 21. Feb 2022, at 04:25, Ben Kehoe ***@***.***> wrote:
> 
> 
> The thing you think is valid is the first three bullets from my revised request above:

I don’t like the term “reference selector” or “reference path".

The kind of singular selector you are trying to identify necessarily returns a singular node set (zero or one nodes) only when given a singular node set.

Indeed, the current definition of “rel-path” ensures that it is built from singular selectors, so it is easier to define value comparison etc.

> 	• Define a reference selector as a selector that returns at most one node.

We don’t have selectors like this (except for $).

> 	• Annotate the root selector, dot selector, and index selector as being reference selectors.
> 	• Define a reference path to be a path consisting only of reference selectors.
> The thing you don't think is valid is slightly different from the fourth bullet, which is not a conversion but an evaluation whether a standard path meets the above definition or not. Even so whether this guidance is in the spec or not is still separable from the above definition being included.
> 
> 	• Recommend or require that implementations support an is_reference_path operation that checks if a path is a reference path or not.

It would certainly be useful to have predicates such as “is_json_path”, “is_normalized_path”, or “is_singular_path” in a JSONPath implementation.
Not sure that this should be mandated in the JSONPath specification, but we could define the third term as well as we already are defining the first two.

Grüße, Carsten

**Comment by benkehoe** [comment]
Sure, the word "reference" just came from the terminology in the Amazon example. The spec could say something like "The root selector, dot selector, and index selector are *singular selectors,* which means they return at most one node. A path that consists only of singular selectors, which will result in at most one node, is termed a *singular path."*

I don't think JSON Pointer is the right way to address this, because, as in the Amazon example, a system may need to accept both standard and singular paths for different parameters, and needing to use wildly different syntax in the same input would be confusing.

**Comment by benkehoe** [comment]
Sure, the word "reference" just came from the terminology in the Amazon example. The spec could say something like "The root selector, dot selector, and index selector are *singular selectors,* which means they return at most one node for each node in their input. A path that consists only of singular selectors, which will result in at most one node for any document, is termed a *singular path."* (I see where I was leaving something out before: for selectors, I said "will return at most one node" when I was implicitly thinking "for each node in their input".)

I don't think JSON Pointer is the right way to address this, because, as in the Amazon example, a system may need to accept both standard and singular paths for different parameters, and needing to use wildly different syntax in the same input would be confusing.

**Comment by gregsdennis** [comment]
Thanks for the clarity. I see now how your proposal addresses the issue.  I have no problem with such a statement in the spec.

I think all that remains is refining the distinction between this concept and the normalized path.  I was under the impression they were the same, and it seems they are not.

**Comment by glyn** [comment]
If I've understood correctly, Normalized Paths are a strict subset of Singular Paths which are a strict subset of JSONPaths.

I'm not convinced of the value of defining Singular Path as a term in the spec if it is not going to be used elsewhere in the spec. If we are going to add auxilliary/unused definitions like this, then we might want to add Plural Path (i.e. a JSONPath which is not a Singular Path), maybe even Empty Path (which returns no nodes, regardless of the JSON document), and other such terms. Adding unused terms to the spec is not cost-free as it bloats the spec and makes it a little harder to read.

If there is a consensus to add Singular Path to the spec, then we have to decide how to specify it. @benkehoe suggests constructing the definition from that of a Singular Selector (adding yet another term). A more straightforward definition would be that a Singular Path is one which returns at most one node for any document.

**Comment by cabo** [comment]
On 2022-02-21, at 09:09, Greg Dennis ***@***.***> wrote:
> 
> I think all that remains is refining the distinction between this concept and the normalized path. I was under the impression they were the same, and it seems they are not.

Being a normalized path is a property of a JSONPath query.
Also, if we define this, being a singular path is another property of a query.
Being normalized implies being singular, but not v.v. (e.g., negative indices).

Now, output paths (a term we are not defining, because it is not a property of a path, but a statement about the way the path was generated) are always normalized paths (and therefore singular, too).

Grüße, Carsten

**Comment by cabo** [comment]
> On 2022-02-21, at 09:26, Glyn Normington ***@***.***> wrote:
> 
> I'm not convinced of the value of defining Singular Path as a term in the spec if it is not going to be used elsewhere in the spec.

I think the place where we nail down the meaning of a rel-path in an expression would be the place where we mention that this has been restricted to get a simple assurance that the path is singular.
So we would indeed have a use for that term.

Grüße, Carsten

**Comment by goessner** [comment]
hmm ... do you have an illustrative example for such an expression ?

**Comment by cabo** [comment]
``` 
$.purchases[?(@.saledate < 20210101)]
``` 

(I would have used `$['vat-increase-date']` but we don't allow `$` in filter expressions.)

`@.saledate` is a `rel-path` and thus a singular path.

**Comment by goessner** [comment]
yes, it makes sense to restrict '@'-expressions to singular pathes. Thus mentioning them as such is enough - not necessarily defining that as term.

I am sure, we allow absolute pathes in filters, as in ...

```
$.colors[?(@ == $.systemColor)]
```

**Comment by benkehoe** [comment]
Defining the term "singular path" would allow a developer to make a precise request of a library owner for support in checking if a path has that property. Without it, a developer has to describe what they want, the library owner has to make up their own term for it, think about the semantics, all the things we've done in this thread. Even though it would be minimally referenced in the spec itself, it would be useful to standardize the language for users of JSON Path.

I think it's additionally useful to extend the term to describe the selectors that comprise singular paths, but that's secondary in my mind.

**Comment by gregsdennis** [comment]
@benkehoe, Same question asked a different way: what does requiring a singular path accomplish/enable that requiring a normalized path cannot?

**Comment by benkehoe** [comment]
Two things:
* Normalized paths use a restricted syntax that's not as likely to be known or understood by users. Especially if standard paths are used in the same interface (as is the case in the Amazon example), having to know you can use `$["foo"]` in one field (that accepts standard paths) but have to put `$['foo']` in another (that requires normalized paths) is going to trip people up every time.
* There are additional paths that are singular that cannot be normalized, negative indexes being the prime example. If the semantic restriction on a given path is "returns at most one node", there are paths that fit that restriction that cannot be represented as normalized paths.

**Comment by timbray** [comment]
Speaking as lead designer of the Amazon States Language and implementer of validators for that language, the "Reference Path" notion was certainly useful at an application level. The very basic description provided at https://states-language.net/#ref-paths drew no complaints that I can remember.  So the evidence suggests that (a) the notion is useful but (b) it's easy enough to cook up your own if you need it.

My position is neutral, i.e. I'll go with whatever the WG is leaning to.

**Comment by benkehoe** [comment]
To close this out, in #164 the term "Singular Path" was defined in the Terminology section, and a grammar for it is defined in the filter selector section, where paths are required to be singular. In an issue like https://github.com/gregsdennis/json-everything/issues/224, a user could ask for replacement of JSON Pointer in an API with JSONPath Singular Paths (whether that's appropriate for a given API is a separate topic!) and a user of a JSONPath library like https://github.com/json-path/JsonPath could ask for an `isSingularPath()` method. Thanks so much!
