### ISSUE TITLE
ANBF for individual selectors shouldn't include brackets

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#159]
The ANBF for the `index-selector` in section 3.5.4 includes the square brackets:

```
index-selector      = "[" S (quoted-member-name / element-index) S "]"
```

Doesn't this preclude the ability to comma-separate multiple indices, e.g. `[1,2,3]`?

(this probably applies to others as well)

**Comment by glyn** [comment]
I think the missing syntax is supplied by:
```
list-selector  = "[" S list-entry 1*(S "," S list-entry) S "]"

list-entry     =  ( quoted-member-name /
                    element-index      /
                    slice-index
                  )
```

**Comment by fiestajetsam** [comment]
Closing this as agreed with the folks at the June interim.
