### ISSUE TITLE
Non-property-name-friendly chars

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#16]
We should probably define what characters are valid for property names.  JSON makes no distinction, so we should support everything.  But this becomes especially important for the dot-property syntax.

The index-property syntax `["name"]` can support any string, so that's not a problem.  (I also think it's a good idea to mirror JSON's escaping requirements for strings.)

But for the dot-property syntax `.name`, I think it's probably a good idea to limit this to alphanumeric characters and underscores: `^[_a-zA-Z0-9]$`.  The following should also be considered:

- Non-English characters
- Starting with a number (many languages don't support starting with a number)
- Emoji and other UTF16 codepoints

**Comment by remorhaz** [comment]
This syntax is being defined [here](https://github.com/jsonpath-standard/internet-draft/pull/13), and there were some discusions related to the problem.

**Comment by gregsdennis** [comment]
I think the current definition of `[-_a-zA-Z0-9\u0080-\u10FFFF]+` is good.  (I understand that `\u10FFFF` isn't in the proper range for Regex, but you get the idea.)

**Comment by gregsdennis** [comment]
So, I ran into a problem with throng to parse `$..book[(@.length-1)]` after I made the change to support thus character set.  Specifically, the parser extracted `length-1` as the property name.

This revealed that expressions will be quite difficult to parse if `-` is allowed in property names.

I think we should remove `-` from the allowed list.

**Comment by gregsdennis** [comment]
Apparently, also relates to (or completely duplicates) #9.

**Comment by glyn** [comment]
> This revealed that expressions will be quite difficult to parse if - is allowed in property names.

Agreed, but I'd prefer to disallow expressions rather than remove `-` from property names as I suspect it's quite commonly used.

**Comment by gregsdennis** [comment]
It's still valid in the quoted-index syntax: `$["dashed-property"]`.

**Comment by gregsdennis** [comment]
> I'd prefer to disallow expressions rather than remove - from property names as I suspect it's quite commonly used.

And expressions aren't commonly used?  You can't just remove expression support: it's part of Goessner's original post, and it's what gives JSON Path it's real power.

Additionally many languages forbid `-` in property names, whereas `_` is allowed.  It's even disallowed in Javascript, the language of the original implementation.

**Comment by gregsdennis** [comment]
Some relevant reading:

- [Python](https://stackoverflow.com/questions/2064329/why-does-python-disallow-usage-of-hyphens-within-function-and-variable-names): not supported
- [C/C++](https://en.wikibooks.org/wiki/C_Programming/Variables#Naming_Variables): not supported
- [Java](https://docs.oracle.com/javase/tutorial/java/nutsandbolts/variables.html): not supported
- [C#](https://stackoverflow.com/questions/12216225/how-do-i-declare-a-variable-with-hyphen-on-it): not supported
- [Go](https://www.digitalocean.com/community/tutorials/how-to-use-variables-and-constants-in-go#naming-variables-rules-and-style): not supported
- [R](https://stackoverflow.com/a/48811387/878701): not supported
- [Swift](https://stackoverflow.com/a/54510804/878701): not supported
- [PHP](https://stackoverflow.com/a/9322340/878701): not supported
- [Javascript](https://stackoverflow.com/q/5516106/878701): only supported with the quoted-indexer syntax, e.g. `value['some-prop']`
- [Ruby](https://www.ruby-forum.com/t/hyphens-in-variable-names/97518/2): only supported with the indexer syntaxes, e.g. `value["some-prop"]` or `value[:some-prop]`
- [Perl](https://perl6advent.wordpress.com/2015/12/05/day-5-identifiers-have-hyphens-in-them/): supported, but variable names are prefixed with `$` to identify them separately from subtraction.  (Still how is `$variable-5` interpreted?)

**Comment by danielaparker** [comment]
I agree with [gregsdennis](https://github.com/gregsdennis)'s opposition to allowing hyphens in unquoted names. Doing so leads to an issue with subtraction in filter expressions, see [Filter expression with subtraction](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_subtraction.html). Given

```
[{"key": 60}, {"key": 50}, {"key": 10}, {"key": -50}, {"key-50": -100}]
```
and selector
```
$[?(@.key-50==-100)]
```
it seems reasonable, consistent with the other arithmetic operations, to expect a result
```
[ { "key": -50  }]
```
11 of the implementations give this result, which includes all of the ones that use javascript as a script engine, and in particular Goessner.

However, if the identifier were determined to be `key-50`, then the result would be
```
{"key-50": -100}
```
13 of the implementations give this result.

More generally, I don't think it's a good idea to allow unquoted names that would be illegal as identifiers in popular interpreters such as javascript.

**Comment by danielaparker** [comment]
To add to  [gregsdennis](https://github.com/gregsdennis)'s list of interpreters that don't support identifiers with hyphens, but have implementations of JSONPath:

 [lua](https://www.lua.org/manual/5.1/)

**Comment by danielaparker** [comment]
On the other side of the story ...

From Christoph Burgmer's comparisons, it appears that [dashes in unquoted names](https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_dash.html) is the consensus. Given
```
{  "key-dash": "value"}
```
the selector
```
$.key-dash
```
results in
```
[  "value"]
```
for most implementations. The consensus includes the important Jayway and Goessner implementations. 

However, Jayway and Goessner part company when it comes to filter expressions. Given
```
[{"key-dash": "value"}]
```
the selector
```
$[*][?(@.key-dash == 'value')]
```
results, in Jayway, in
```
[{"key-dash" : "value"}]
```
and, in Goessner, in
```
jsonPath: dash is not defined: _v.key-dash == 'value'
```
When a JavaScript interpretor is used for the "script engine", the rules for identifiers are the rules for the script engine.

**Comment by gregsdennis** [comment]
> Implementations that employ a scripting language for evaluating expressions must follow the rules for that scripting language.

Part of this proposal is to define an expression language that is independent of the language the implementation is written in. Only by doing this can a path string be interoperable between systems.

Interoperability needs to be something that we can't waiver on if we want wide acceptance.

**Comment by danielaparker** [comment]
Just as a footnote, for comparison, [JMESPath identifiers](https://jmespath.org/specification.html#identifiers) do not allow hyphens in unquoted strings.

**Comment by danielaparker** [comment]
> > This revealed that expressions will be quite difficult to parse if - is allowed in property names.
> 
> Agreed, but I'd prefer to disallow expressions rather than remove `-` from property names as I suspect it's quite commonly used.

Most (all?) implementations that do allow dashes in unquoted names in expressions don't attempt anything difficult in parsing, rather, they requires the user to be aware that a minus sign must be separated from such a name with a space character. Some implementations allow dashes in unquoted names in the main path but not in expressions or filter expressions, e.g. given, 
```
[{"key-a": "first", "key-b": "second", "key-c": "third"}]
```
Javascript Goessner, which uses Javascript for an "expression script", allows 
```
$[*].key-b
```
but not
```
$[?(@.key-b == 'second')]
```
The argument in favor of allowing dashes is to accommodate legacy implementations, the argument against is to have a cleaner language. Now that Stefan Goessner has lent his authority to [_not_ allowing dashes](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-jsonpath/issues/53), perhaps it's time to frame this as a decision point and open it to debate?

**Comment by goessner** [comment]
> Most (all?) implementations that support a dash in unquoted names don't attempt anything difficult when parsing expressions.

So we obviously see here 'the normative power of the factual', which is usually hard to ignore.

> Comparing [Dot notation with dash](https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_dash.html) and [Filter expression with subtraction](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_subtraction.html), implementations that support a dash in unquoted names generally give precedence to dash interpreted as part of identifier, and the user has to know to put a space before a minus sign, 13 implementations take that approach. The exception are implementations that allow a dash in unquoted names in the primary path, but not in filter expressions, most notably Javascript Goessner, which uses Javascript as a "script engine". The inattentive user may experience surprising results.

Thanks for bringing this up. In fact I never intended to allow dashes with dot notation, in the same way, as JavaScript disallows them inside of variable names. Maybe I should have tested those simple regular expressions, I used in my initial implementation, more carefully. Having access to Christoph Burgmer's tests would have been highly valuable at that time.

Of course I respect and even share the idea of being careful with breaking existing implementations.

By the way:
* I enjoyed Tim Bray's '[Jsonpath] JSONpath corner case' in this context. 
* I am carefully reading through the Mail Archive at current (from past to present) ...
* ... what should have been my first activity here. 
* I am not aware, how to link into that archive.

**Comment by glyn** [comment]
On 09/02/2021 19:11, Stefan Goessner wrote:
> I am not aware, how to link into that archive.

1. View the archive at https://mailarchive.ietf.org/arch/browse/jsonpath/.

2. Find a post.

3. Click on the link symbol named "Message detail" shown at the top 
right of the attached screenshot.

4. Copy the URL of the item.

**Comment by glyn** [comment]
> I am not aware, how to link into that archive.

1. View the archive at https://mailarchive.ietf.org/arch/browse/jsonpath/.

2. Find a post.

3. Click on the link symbol named "Message detail" shown at the top
right of the screenshot below.

4. Copy the URL of the item.


![Screenshot from 2021-02-15 03-41-40](https://user-images.githubusercontent.com/94953/107903248-a3b3ed00-6f40-11eb-9b78-e819a5a199af.png)

**Comment by danielaparker** [comment]
@gregsdennis wrote:

> So, I ran into a problem with trying to parse `$..book[(@.length-1)]` after I made the change to support thus character set. Specifically, the parser extracted `length-1` as the property name.
> 
> This revealed that expressions will be quite difficult to parse if `-` is allowed in property names.
> 
> I think we should remove `-` from the allowed list.

In support of this proposal, while it has been claimed that legacy implementations support a dash in unquoted names, that's only partly true.

It is true that In the main path, [most legacy implementations support](https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_dash.html) a dash, as in
```
$[?(@.key-dash == 'value')]
```
However, in filter predicates, as in
```
$[?(@.key-dash == 'value')]
```
there is [no such consensus](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_dot_notation_with_dash.html). Only 13 out of 41 implementations support a dash in unquoted names in filter predicates, most do not. 

I think it's unlikely that a JSONPath specification will want to accept different naming conventions in the main path and in filter predicates. Hence, even with respect for legacy behaviour as a motivating factor, a decision will need to be made. And, as noted, allowing a dash in unquoted names in filter predicates causes trouble.
