### ISSUE TITLE
Mention SQL/JSON Path Expression

### ISSUE THREAD

**Issue by nichtich** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#161]
**SQL/JSON Path Expression** (as specified in [SQL ISO standard](https://www.iso.org/standard/78937.html)) was heavily inspired by JSONPath, overlaps in both syntax and semantics and has a similar name. I'm sure there is a common subset of both languages, but finding out the exact edge cases and differences would be an unreasonable demand. Anyway, this is and will be source of confusion and subtle bugs in applications that wrongly assume to know which JSON query language they are using.

The JSONPath RFC should at least mention ISO SQL/JSON Path Expression to make clear that its not the same and incompatibilities should be expected when using JSON Path Expressions as JSONPath or the reverse.

**Comment by gregsdennis** [comment]
I'm not certain its feasible to make mention of specific related technologies.  How do we decide which ones are mentioned?

**Comment by cabo** [comment]
As we make all decisions: Deliberate, let the WG decide.
The answer doesn't have to be right, we just need consensus.
(I do have higher standards for the decisions that influence interoperability, but this one is a toss.)
The fact that there is not a single technically correct answer for an issue doesn't mean that we must not decide it.

I think such a reference would be indicated where we can reduce confusion (e.g., where the other thing is also called something similar to JSONPath), or where the technical exposition would benefit from contrasting our approach to the other one.  So far, nothing triggered either of these, I think (except for XPath, for which we have an appendix).

**Comment by nichtich** [comment]
I think a simple sentence would be enough, for instance

> JSONPath partly shares syntax and semantics with SQL/JSON Path Language (ISO/IEC 19075-6:2021) but differs in substantial parts.

or

> JSONPath was inspired by XPath and inspired other query languages such as SQL/JSON Path Language.

The influence of JSONPath to SQL/JSON Path Language is undeniable.

**Comment by cabo** [comment]
There are a lot of languages that have been inspired by JSONPath.  We don't really want to do an extensive survey here.  Agreed at 2022-06-14 interim.
