### ISSUE TITLE
Make @ optional in filter selectors

### ISSUE THREAD

**Issue by nichtich** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#162]
The grammar includes `"@"` only it at `rel-path` rule in filter expressions. `rel-path` is only used in rule `path`:

    path         = rel-path / json-path
    rel-path     = "@" *(S (dot-selector / index-selector))

As `json-path` always starts with `$`, a parser does not need the `"@"` to distinguish between `rel-path` and `json-path`, so the character can be made optional, helping JSONPath expressions look less like obfuscated Per (SCNR).

Example:

    $[? @.key>42 && @.key<44 ]
    $[?  .key>42 &&  .key<44 ]

The latter is more readable, isn't it?

**Comment by cabo** [comment]
We could do this.
Matters of taste aside (I find the version with the @ sign to be more readable), this would be an innovation unless existing implementations already are doing this.
We are not chartered to innovate, except where this is necessary to achieve an interoperable (and evolvable) situation.

**Comment by nichtich** [comment]
I guess you are accustomed to the `@` so feels natural, but from a usability point of view it is noise and confusing (what's the difference between `@.foo` and `.foo`?  Why is `$.foo` allowed at the root but not `@.foo`?...) *except* when you are already used to it. Making it optional would not break existing JSONPath expressions but it would make existing implementations lack support of a new feature. You decide what weights more: simplicity and usability or keeping existing implementations fully compliant with the spec. As far as I understand, parenthesis in filter expressions (`[?(...)]`) have also been dropped although they were mandatory.

Another argument *against* making `@` optional would be to better align with SQL/JSON Path Expression Syntax.

**Comment by timbray** [comment]
This is treated as editorial input and we'll ask our editors to consider providing such a rationale.

**Comment by glyn** [comment]
I'm not sure what needs adding given [section 1.2](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#name-history) includes the following general rationale:

> JSONPath was intended as a light-weight companion to JSON implementations on platforms such as PHP and JavaScript, so instead of defining its own expression language like XPath did, JSONPath delegated this to the expression language of the platform. While the languages in which JSONPath is used do have significant commonalities, over time this caused non-portability of JSONPath expressions between the ensuing platform-specific dialects.
>
> The present specification intends to remove platform dependencies and serve as a common JSONPath specification that can be used across platforms. [...]

**Comment by glyn** [comment]
Closing, assuming no further rationale is needed. Please re-open if necessary.
