### ISSUE TITLE
Specify handing of null

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#171]
The current spec is silent about how `null` is handled in many situations:

1. What is the result of applying the JSONPath `$` to the JSON document `null`?
2. What is the result of applying the JSONPath `$.*` to the JSON document `{"a": null}`? The [comparison consensus](https://cburgmer.github.io/json-path-comparison/results/dot_notation_on_null_value.html) implies a node set with the single value `null`.
3. What is the result of applying the JSONPath `$[*]` to the JSON document `[null]`? The [comparison consensus](https://cburgmer.github.io/json-path-comparison/results/bracket_notation_with_wildcard_on_null_value_array.html) implies a node set with the single value `null`.
4. What is the result of applying the JSONPath `$[0]` to the JSON document `[null]`? Presumably a node set with the single value `null`.
5. What is the result of applying the JSONPath `$[1:2]` to the JSON document `["a", null, "b"]`? Presumably a node set with the values `"a"` and `null`.
6. What is the result of applying the JSONPath `$[?@]` to the JSON document `["a", null, "b"]`?
7. What is the result of applying the JSONPath `$[?@.a]` to the JSON document `[{"a": null}]`?
8. What is the result of applying the JSONPath `$.null` to the JSON document `{"null": "value"}`? The [comparison consensus](https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_key_named_null.html) implies a node set with the single value `"value"`.

**Comment by cburgmer** [comment]
To 1.: Similar is https://cburgmer.github.io/json-path-comparison/results/root_on_scalar_false.html
To 6.: https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_current_object.html
To 7.: https://cburgmer.github.io/json-path-comparison/results/filter_expression_without_value.html

**Comment by gregsdennis** [comment]
I have historically handles `null` as a valid value (contrary to most of .net) separate from "undefined" or "missing."  As a result, I agree with these points.

Specifically for [7], this is an existence test. Since `a` exists as a property in the object, that object would be returned.  I believe we decided that existence testing does not consider falsiness.
