### ISSUE TITLE
Descendant semantics

### ISSUE THREAD

**Issue by bram209** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#177]
### Dot Wildcard Selector
> A dot-wild-selector acts as a wildcard by selecting the nodes of all member values of an object in its input nodelist as well as all element nodes of an array in its input nodelist.

Considering the following input:
```json
{
  "o": {"j": 1, "k": 2},
  "a": [5, 3]
}
```

`$.*` would evaluate to (in this case the values of the object):

```json
[
  {"j": 1, "k": 2},
  [5, 3]
]
```

### Descendant Selector

I would expect the descendant version: `$..*` to evaluate to:
```json
[
  {"j": 1, "k": 2},
  [5, 3],
  1,
  2,
  5,
  3
]
```

Yet the example says:
```json
[
  { "o": {"j": 1, "k": 2}, "a": [5, 3] }, // full input is selected, even tho the dot wildcard selector would only select the object values
  {"j": 1, "k": 2},
  [5, 3],
  1,
  2,
  5,
  3
]
```
Considering the following pseudo logic:
```
function traverse(json_value, child_selector) {
     if (json_value == array) {
          return child_selector.select(json_value) + json_value.map(x => traverse(x, child_selector));
    } else if (json_value == object) {
          return child_selector.select(json_value) + json_value.values.map(x => traverse(x, child_selector));
   } else {
         return [];
   }
}
```

In the case of `$..*` the `child_selector` would be an index wildcard selector.

### Expected Descendant semantics
I would expect the descendant selector to (starting by selecting itself) walk through the json structure and select all the results by applying the child selector (dot-member-name, index-selector, index-wild-selector, or wildcard) on each traversed value.

Am I misunderstanding something here or is this the intended behavior?

**Comment by glyn** [comment]
Thanks for raising this. When I was writing the example, I noticed that only a few implementations included the node itself. But the descendant selector semantics currently say:
> The descendant-selector selects the node and all its descendants.

and so I included the "starting" node itself. This is why I included the following text in the commit message:

> [Note] that contrary to the consensus of the comparison project (below), the root node appears in the results of $..* and $..[*].
> 
>    https://cburgmer.github.io/json-path-comparison/results/dot_notation_with_wildcard_after_recursive_descent.html

The semantics section needs improving anyway to clarify the semantics of the various forms of the descendants selector. I agree with the semantics proposed above, providing there is a consensus for this in the WG.

**Comment by goessner** [comment]
In my understanding descendant selector `$..*` simply extends the single-level operating of child selector `$.*` , in that it further recursively operates on all other descendant levels.

So I agree to Bram's traversal algorithm above.

A node is not considered a descendant of itself. Obviously I have not been aware of this behavior.
