### ISSUE TITLE
Extension support

### ISSUE THREAD

**Issue by fiestajetsam** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#194]
Cover how the extension mechanism, including updates to IANA work.

**Comment by danielaparker** [comment]
Why? The draft specification is already somewhat incompatible with all existing implementations, all existing implementations would see major breaking changes were they to move to conformity with the draft. Why then allow for additional incompatibilities between new implementations that follow the draft? It seems to me that the primary value of the draft is inter operability, and extensions break interoperability.

**Comment by cabo** [comment]
> Why? The draft specification is already somewhat incompatible with all existing implementations, all existing implementations would see major breaking changes were they to move to conformity with the draft. Why then allow for additional incompatibilities between new implementations that follow the draft? It seems to me that the primary value of the draft is interoperability, and extensions break interoperability.

The damage done by extensions is larger when they are done in an uncontrolled, chaotic fashion.  And they will be, if we don't define an extension point.

**Comment by goessner** [comment]
Thanks for enlightening ... reading RFC 8126 ...

**Comment by glyn** [comment]
The function extension point is in base 09. I think addresses the general points in this issue in a concrete way.
