### ISSUE TITLE
github action to check the XML and ABNF

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#2]
It would be good to automate a check based on the authoring instructions in the README, so that we don't accidentally check in incorrect XML source or invalid ABNF (although it's invalid at the time of writing because the draft hasn't got any ABNF yet!).

**Comment by cabo** [comment]
This should be done by moving to Martin Thomson's I-D template, which has active development.

**Comment by cabo** [comment]
We have moved to I-D-template and have a scripts/gen.sh that does the check.
A check-in check would be possible, but maybe unnecessary.

**Comment by glyn** [comment]
Now we have moved to kramdown source, the XML check is unnecessary.

However, a [PR with invalid ABNF](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/133) passes all checks, so a github action, e.g. to fail if `scripts/gen.sh` fails, is still be nice to have.

**Comment by cabo** [comment]
OK, I have put on a "task" label -- this is not an issue with the document.

**Comment by cabo** [comment]
As long as we check the ABNF manually with the script, this remains a nice-to-have that is not needed for completing -base.
Right now the ABNF is missing a definition, but it is also actively worked on in #145.

**Comment by fiestajetsam** [comment]
Consensus made at the January 2022 interim is that this is wontfix, so, let's just close it.
