### ISSUE TITLE
absent >= absent?

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#209]
(This is a follow-on from https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/123)

https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/207 covers comparing absent with absent using == and !=, but we still haven't decided what to do about the likes of "absent >= absent". The spec currently says:

> Comparisons using one of the operators <, <=, >, and >= are between numeric values only. Using these operators to compare other types of values produces a "false" comparison result.

This doesn't make it clear what to do when comparing two singular paths which each select no value.

I can see two options:

1. We might want "absent >= absent" to be true because "absent == absent" is true.

2. We might say that "absent" isn't a numeric value and so "absent >= absent" is false.

I prefer the first option as it preserves the usual law that "x >= y" if and only if "x >y" OR "x ==y". (I guess we might want to add such laws to the spec too!)

**Comment by gregsdennis** [comment]
I, too, prefer the first option.

**Comment by danielaparker** [comment]
If your model is Javascript and "absent" has the same properties as "undefined", then inequality operators wouldn't be supported. If your model is a language that supports the notion of "optional", I can't think of any that support inequality operators for values of that type. But on this, the draft really needs to define its type system more precisely, as introducing the notion of "absent" extends the type system beyond JSON.

**Comment by glyn** [comment]
According to the spec, the results of singular paths are nodelists consisting of at most one node. So one way to address this issue would be to say that:

* when a nodelist consisting of a single node appears in a comparison, it is replaced by the value of the node, and
* when an empty nodelist appears in a comparison, the result of the comparison is true if and only if the comparison is being made with another empty nodelist and the comparison operation is `==`, `>=` or `<=`.

**Comment by danielaparker** [comment]
You also have to think about what it means for an expression that evaluates to "absent" to be passed to a function (assuming the draft supports functions.) By comparison, in Javascript, a value of type undefined is passed to the function.
