### ISSUE TITLE
Clarify that index selector only applies to arrays

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#216]
The index selector (but _not_ the index wildcard selector) selects no elements from non-arrays.

See https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/215#issuecomment-1175522531 for background.

**Comment by gregsdennis** [comment]
This seems implicit since JSON objects cannot be numerically accessed.

**Comment by glyn** [comment]
Yes, but making it explicit is clearer.
