### ISSUE TITLE
Expand descendant selector to allow following with any bracket syntax

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#219]
Currently the spec only permits `..foo`, `..*, `..[*]`, and `..[1]`.  I think it would be beneficial and trivial to also allow the other bracketed query syntaxes:

- `..['foo']` (I expect this should already be supported since `..foo` is, but it doesn't seem to be)
- `..[1:2]`
- `..[?(@.foo == 1)]`

**Comment by glyn** [comment]
Descendants with quoted member names, such as `..['foo']`,  are already supported:
```
descendant-selector = ".." ( dot-member-name      /  ; ..<name>
                             index-selector       /  ; ..[<index>]
                             index-wild-selector  /  ; ..[*]
                             "*"                     ; ..*
                           )

index-selector      = "[" S (quoted-member-name / element-index) S "]"
```

**Comment by glyn** [comment]
Here are the relevant tests from the comparison project.

Lack of consensus for descendant/filter:
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_after_recursive_descent.html
* https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_value_false.html

Consensus for descendant/list:
* https://cburgmer.github.io/json-path-comparison/results/union_with_keys_after_recursive_descent.html

(Context: https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/220#issuecomment-1179564663.)
