### ISSUE TITLE
Whitespace allowances

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#24]
Do we allow spaces (outside of string literals)?  If so, where is whitespace allowed?

I think whitespace in query expressions should be allowed.  This would fall in to the context of the [query expression syntax](https://github.com/jsonpath-standard/internet-draft/issues/17).

```
$[(@length - 1)]
$[?(@.value < 10)]
```

Maybe inside the union/[indexer](https://github.com/jsonpath-standard/internet-draft/issues/21) selector:

```
$[ 1, 2, 5:7, "prop" ]
```

Are there any other places where whitespace could be considered useful?

**Comment by remorhaz** [comment]
It may be convenient to allow spaces between matchers - to allow well-readable multi-line queries for complex cases.

**Comment by gregsdennis** [comment]
Looks like the [current definition of a slice](https://github.com/jsonpath-standard/internet-draft/pull/28) allows whitespace internally, so that ` 1 : 2 : 3 ` is valid.

**Comment by cabo** [comment]
Closed in #131 and #132

**Comment by gregsdennis** [comment]
What was the resolution here?  Where did we end up allowing whitespace?
