### ISSUE TITLE
Crush spaces?

### ISSUE THREAD

**Issue by timbray** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#273]
There are lots of places in the grammar where optional space is allowed, e.g. 

```
slice-selector =  [start S] ":" S [end S] [":" [S step ]]
```

Would it be a good idea to crush them all out? We wouldn't lose any backward compatibility, we'd remove a lot of optional operations for implementers, and we'd get more compatible expressions. We might lose readability, but not much.

**Comment by timbray** [comment]
Not passionate about this one, but I do like the idea of removing them from slices.

**Comment by glyn** [comment]
In addition to removing whitespace from slices, we might also consider removing all whitespace, except that following the comma selector separator from child (and hence descendant) segments, i.e. replacing:
```
child-longhand            = "[" S selector 1*(S "," S selector) S "]"
```
with
```
child-longhand            = "[" selector 1*("," S selector) "]"
```

**Comment by glyn** [comment]
I did think of a readability concern for slices. Suppose there is some kind of list of paths and it was more readable to line up the slice components, e.g.:
```
$[  0 :   5 : 2]
$[ 10 :  15 : 2]
$[ 20 :  25 : 2]
$[ 30 :  35 : 2]
...
$[100 : 105 : 2]
```
Compare this to the crushed alternative:
```
$[0:5:2]
$[10:15:2]
$[20:25:2]
$[30:35:2]
...
$[100:105:2]
```

I'm not sure that's a deal-breaker for "crushed" slices, but it's worth thinking about.

**Comment by cabo** [comment]
Blank space also includes newlines.  Some queries may be long enough that you want to break lines; not being able to do this on natural breaks such as `:` can be counterintuitive.

**Comment by cabo** [comment]
After deciding this issue, continue in #344
