### ISSUE TITLE
Table 15

### ISSUE THREAD

**Issue by timbray** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#274]
The last entry in table 15 is completely incomprehensible and the explanation in the following paragraph doesn't help.  Not sure how to work around this within the limitations of xml2rfc but maybe just leave it out, it's implicit in the 2nd-last-line example.

**Comment by glyn** [comment]
@timbray I presume you are referring to [Table 15 in draft 07](https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-07.html#table-15) with the caption "Normalized Path examples". (Table 15 at `HEAD` is a different one.)

I agree the example is a mess and doesn't pull its weight, so I'll submit a PR to delete it.

**Comment by cabo** [comment]
I think it is useful to have an example that shows characters are not normally escaped, even if they are beyond ASCII.

**Comment by cabo** [comment]
(By the time this goes by the RFC editor, we may be able to get rid of the useless U+.... stuff added by xml2rfc.)
