### ISSUE TITLE
consensus on the term "current node"

### ISSUE THREAD

**Issue by goessner** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#285]
The term "current node" is traditionally used with iterating over children of structured nodes in filter selectors.

Now it also appears in 3.3 Semantics chapter in a different context:

```
A segment performs its function on each of the nodes in its input
nodelist, during such a function execution, such a node is referred
to as the "current node".
```

To avoid confusion of readers, we might use a different term there. A good alternative would be "context node", which is also used by XPath in a similar context.

**Comment by glyn** [comment]
Perhaps a simple solution would be to avoid the use of the term in 3.3 as this term doesn't appear to be used elsewhere.

**Comment by glyn** [comment]
Please see the simplification in https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/286.
