### ISSUE TITLE
Are function extensions defined in the spec mandatory?

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#323]
The spec defines a number of function extensions which will become the initial entries in the IANA sub-registry. Are these extensions optional for JSONPath implementations (like subsequent sub-registry entries) or mandatory because they are in the spec?

**Comment by gregsdennis** [comment]
As being party of the core document, users will probably expect implementations to support them.

**Comment by glyn** [comment]
That's true, unless we make it clear that needn't be the case.

I would prefer function extensions all to be on the same footing, regardless of whether they are in the JSONPath spec or added later. It seems rather arbitrary to make those function extensions in the JSONPath spec mandatory given that they are merely the initial entries in the IANA sub-registry.

So I think the spec should say that a JSONPath implementation MAY implement all, some, or none of the function extensions included in the spec. This leaves open the possibility of a basic implementation omitting function extensions altogether.

**Comment by cabo** [comment]
I would prefer to make these extensions mandatory.
This increases interoperability; these mechanisms are phrased as function extensions because that is a convenient way to define them, not because they are optional.
Having mandatory function extensions also makes sure the extension point itself needs to be implemented.

**Comment by gregsdennis** [comment]
I concur with @cabo

**Comment by cabo** [comment]
2023-01-10 Interim: Document that the functions are non-optional.
