### ISSUE TITLE
Function extension access to node location

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#324]
Function extensions can take arguments of kind nodelist. May a function extension make use of a node's location?

If so, it may be possible to define an index_or_member_name() function.

If not, we need to say so in the spec.

**Comment by gregsdennis** [comment]
This would also require implementations to support returning locations rather than merely node values.

**Comment by glyn** [comment]
> This would also require implementations to support returning locations rather than merely node values.

This is already the case. Function extensions can return nodelists which consist of nodes, each of which has a location and a value. The spec doesn't talk about function extensions returning node values: they either return a nodelist or a value.

**Comment by glyn** [comment]
I think this issue can be closed now. I think there is enough details to avoid poeple getting the wrong idea.
