### ISSUE TITLE
Deduplication in the count() function extension

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#325]
As currently specified, there is no deduplication of nodes input to the count() function extension. But the spec contains a placeholder suggesting discussion of deduplication. This issue is for that discussion.

This issue is related to https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/324 because if function extensions do not have access to node location, then it would not be possible to deduplicate on node identity, only potentially on value.

**Comment by cabo** [comment]
2023-01-10 Interim: Remove the editor's note now.
