### ISSUE TITLE
Cardinality of nodelists returned by function extensions

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#327]
Currently function extensions that return a nodelist must return a nodelist consisting of a single node.

When a function extension is used as a comparable, it should be able to return an empty nodelist.

When a function extension is used in an existence test, it should be able to return any number of nodes in its nodelist. (Currently, such an existence test always yields true since the returned nodelist is non-empty.)

**Comment by gregsdennis** [comment]
Also if a function is used as an input to another function, it should be allowed to return multiple nodes.

**Comment by glyn** [comment]
> Also if a function is used as an input to another function, it should be allowed to return multiple nodes.

Agreed. PR 330 addresses this.
