### ISSUE TITLE
Advanced usages of expressions

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#335]
Would we consider allowing advanced expressions usages?

### As a `comparable` (as named in the ABNF)

```
Path
    $[?@.foo == (@.bar < 10)]

Data:
    [
      { "id": 1, "foo": true, "bar": 5 },
      { "id": 2, "foo": false, "bar": 5 },
      { "id": 3, "foo": true, "bar": 50 },
      { "id": 4, "foo": false, "bar": 50 }
    ]
```

This would return the objects with `id`s 1 and 4.

### As a function argument:

```
Path
    $[?sqrt(@.foo + @.bar) < 10)] 

Data:
    [
      { "id": 1, "foo": 5, "bar": 5 },
      { "id": 2, "foo": 50, "bar": 51 }
    ]
```

(Yeah, we don't support `+` currently, but the example illustrates the idea.)

This would return the object with `id` 1.

There are probably other ways expressions could be used, too.

**Comment by glyn** [comment]
Note that function extensions, with the improvements anticipated in https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/pull/330, may be able to address the above use cases:
```
$[?@.foo == lessThan(@.bar, 10)]

$[?sqrt(add(@.foo, @.bar)) < 10)]
```

**Comment by gregsdennis** [comment]
I think what I've written is probably the more intuitive given the gamut of features in programming languages available today.  What you have is definitely more functional (i.e. functional programming style), but I would tend toward using the operators for these examples.

**Comment by gregsdennis** [comment]
Interestingly, I found a test in the comparison project that treats an expression as a `comparable`:  `$[?((@.key<44)==false)]`.

**Comment by glyn** [comment]
> $[?((@.key<44)==false)]

Here's [a link to the test](https://cburgmer.github.io/json-path-comparison/results/filter_expression_with_equals_boolean_expression_value.html). There is no consensus among implementations, although 14 of them behave the way this issue is proposing. (Embarrassingly, my Go implementation gets just the opposite of that result. That looks like a bug IIRC.)

**Comment by cabo** [comment]
2023-01-10 Interim: Do not do this enhancement.
