### ISSUE TITLE
Index selector [-0]

### ISSUE THREAD

**Issue by LutzBettge** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#337]
According to chapter 2.5.3, using -0 as index is allowed, but no semantics for this is defined (and probably should not be defined).
Proposal would be to exclude -0, i.e. replace the line

int = ["-"] ( "0" / (DIGIT1 *DIGIT) ) ; - optional

by

int = ( "0" / ["-"] (DIGIT1 *DIGIT) ) ; - optional

This also makes sense for all other occurrences of "int" in the document.

**Comment by cabo** [comment]
Very good point.
I'll create a PR.
