### ISSUE TITLE
Clarify behaviour of existence test with OptionalBoolean function

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#345]
Currently, the existence test description contradicts the intended use of OptionalBoolean functions. We need to be careful if we want to make a special case for OptionalBoolean functions and not open the door to any boolean value being treated similarly.

**Comment by cabo** [comment]
2023-01-10 Interim: Fix text to properly handle OptionalBoolean.

**Comment by gregsdennis** [comment]
Can this issue be elaborated?  What is OptionalBoolean?  How does this apply to functions?  Examples would be great.

**Comment by glyn** [comment]
Base 09 explains what OptionalBoolean is and uses it in the match and search functions. The current issue will also add some text to explain the way OptionalBoolean functions behave in filter expressions.
