### ISSUE TITLE
The examples for `match()` conflate boolean values with boolean expresion results

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#360]
For filter expressions, we have made a distinction between the JSON literals `true`/`false` and the result of a comparison (i.e. `$[?@.a]` is different from `$[?@.a == true]`).  However the examples for the `match()` function seem to conflict with this idea.

```jsonpath
$[?match(@.timezone, 'Europe/.*')]
$[?match(@.timezone, 'Europe/.*') == true]
```

The returns for `match()` and `search()` are described as

> Result: `OptionalBoolean` (`true`, `false`, or `Nothing`)

I think that this implies the latter would be valid, but the former would imply that the `match()` function can operate as an existence test akin to `$[?@.a]`, which doesn't make sense.  I don't think the function is testing whether a match exists, but whether the value is a match.

The only way I can see the former being valid is if the first argument allowed for a nodelist, but then that would make the latter feel weird (and [potentially only fail at runtime](https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-base/issues/359)).

It _could_ be defined so that:

- if a singular path is used for the first argument, then it MUST be compared to a literal
- if a plural (?) path is used for the first argument, then it MUST NOT be compared to a literal (it MUST be an existence test)

This would resolve the ambiguity and allow for parsing to handle things, but context-sensitive grammar is tricky.

**Comment by cabo** [comment]
I'm not sure you saw:

```
A test expression either tests the existence of a node
designated by an embedded query (see {{extest}}) or tests the
result of a function expression (see {{fnex}}).
In the latter case, if the function expression is of type
`OptionalBoolean` or one of its subtypes, it tests whether the result
is `true`; if the function expression is of type `OptionalNodes` or
one of its subtypes, it tests whether the result is different from
`Nothing`.
```

(https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#section-2.5.5.1-6)

**Comment by gregsdennis** [comment]
I'm making the point that this is confusing.  Why have both when we've clearly defined that JSON literals are not treated this way (for which we have good reason)?

**Comment by gregsdennis** [comment]
In re-reading this, I see the difference between returning a `Value` which may be a boolean and returning a `Boolean`.

Since we make that distinction, I would now expect that

```jsonpath
$[?match(@.timezone, 'Europe/.*') == true]
```

would be invalid as it's comparing a `Boolean` to a `Value`, which we've disallowed.  `==` must only operate on `Value`s.

**Comment by gregsdennis** [comment]
_However_...

(I'm working on implementing this)

this does mean that we effectively have two kinds of functions:

- value functions (e.g. `length()`) which return a `comparable`
- boolean functions (e.g. `match()`) which return a `Boolean`

From a user perspective, I think I prefer this as it allows the syntax without the `== true`.  However such functions would never be supported as a `comparable`.  They could be operands of `&&` and `||`, but never `==` or `>`.

From an implementor perspective, it's a bit more that I have to consider because I have to make two kinds of functions.  Whereas if `match()` simply returned a `Value` that contains a boolean (like `length()` returns a `Value` that contains an integer), then I only have to make a "value function."

I think the user perspective takes precedence here, even though it's a bit more work for me.
