### ISSUE TITLE
Why does `length()` return 1 for unsupported inputs?

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#361]
For `length()`, the spec defines 

> Its only argument is a value (possibly taken from a singular path as in the example above). The result also is a value, an unsigned integer.
> 
> - If the argument value is a string, the result is the number of Unicode scalar values in the string.
> - If the argument value is an array, the result is the number of elements in the array.
> - If the argument value is an object, the result is the number of members in the object.
> - For any other argument value, the result is one.

Why return 1?  That's a possible value for `length()` to return for valid inputs.  Wouldn't it make sense to return a value that _can't_ be returned by a valid input, like -1?

```jsonpath
$[?length(@.authors) == 1]
```

```json
[
  { "data": "no authors here" },
  { "authors": [ "a single author" ] }
]
```

Currently, this returns the both objects in the array, which is counter-intuitive.  The length of the `authors` property in `{"data": "no authors here" }` is nonsensical because it doesn't contain an `authors` property.

**Comment by cabo** [comment]
Well, I picked this hoping people would notice this...

We have two different cases that probably also need different answers.

The one the text addresses: A non-container, non-string value, e.g., length(3)
I think I can argue that 1 is a good value for that.

The one the text does not address: An empty nodelist (Nothing).
1 is definitely not a good value for that.  
Nothing speaks for -1 except FORTRAN-era conventions.
I think we want to be able to return Nothing here.

**Comment by gregsdennis** [comment]
> The one the text addresses: A non-container, non-string value, e.g., length(3)
> I think I can argue that 1 is a good value for that.

I disagree.  I don't think the "length" of `3` is 1.  I think it's nonsensical.

> I think we want to be able to return Nothing here.

I'm happy with this.

**Comment by glyn** [comment]
I'd be comfortable with `length(3)` returning `Nothing`.
