### ISSUE TITLE
Escaping string literals in filter expressions

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#362]
The ABNF declares that string literals in filter expressions need to be escaped as defined by JSON.  (See definition of `string-literal` in section [2.5.1](https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-09.html#name-name-selector) and its use in section [2.5.5](https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-09.html#name-filter-selector)).  Does this extend to function parameters, and specifically iregexp literals for `match()` and `search()`?

How would the regex `2022-01-\d{2}` be represented in a path?  Would you just use that directly, or would it need to be escaped as `2022-01-\\d{2}`?

Personally, I'm in favor of escaping it for consistency.  (It also makes my code a lot cleaner to not have to special-case where I might expect a regex.)

**Comment by cabo** [comment]
On 2023-01-19, at 00:07, Greg Dennis ***@***.***> wrote:
> 
> 
> The ABNF declares that string literals in filter expressions need to be escaped as defined by JSON. (See definition of string-literal in section 2.5.1 and its use in section 2.5.5).  Does this extend to function parameters, and specifically iregexp literals for match() and search()?

Yes.

There is nothing special about literals passed to function extensions.

> How would the regex 2022-01-\d{2} be represented in a path? Would you just use that directly, or would it need to be escaped as 2022-01-\\d{2}?

The latter.
(Except that iregexp doesn’t include \d; use [0-9] or \p{Nd} depending on what you actually mean.)

Grüße, Carsten
