### ISSUE TITLE
`Value` in Table 13 is confusing

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#366]
If I'm reading the [table](https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-09.html#tbl-types) right, it looks like the term `Value` is being used to mean different things depending on which column it's in.

- In column 1 ("Type") or column 3 ("Subtypes"), it's referring to the type system we're creating.
- In column 2 ("Abstract Instances"), it's referring to the underlying JSON(ish) value kind, i.e. `object`, `boolean`, `number`, etc, plus `Nothing`.

I think having the same word to define these things can be confusing for the reader, and maybe we need something else in one of these places to indicate the distinction.  We've already done this for the `Absent` type to distinguish it from the `Nothing` value.

**Comment by glyn** [comment]
I'm not sure there is a really good alternative. We could use `JSONValue` for abstract instances, but in the rest of the spec, "value" implies a JSON value, so this doesn't seem quite right.

**Comment by gregsdennis** [comment]
If "value" implies a JSON value (corresponding to the middle column), then we should change the others (the type name).  It really is confusing.

**Comment by gregsdennis** [comment]
In the interim, we decided to append the type names with "Type".  I will create a PR for this.

**Comment by gregsdennis** [comment]
I'm going to wait for #386 to complete before going forward with this as they change the same chunk of text.

**Comment by glyn** [comment]
> I'm going to wait for #386 to complete before going forward with this as they change the same chunk of text.

Thanks. That's why I am trying to tidy up #386 and get it merged ASAP.
