### ISSUE TITLE
Clarify syntax of strings in match and search regexp arguments

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#367]
Currently the spec doesn't make it completely clear whether regexp strings need to be enclosed in double quotes or whether single quotes are also acceptable.

My reading of the normative parts of the current spec is that the arguments need to be enclosed in double quotes because they must be of type Value. If this is the intention, we should provide an example showing single quotes are not allowed. Currently, there is an example showing that single quotes **are** allowed.

**Comment by gregsdennis** [comment]
This seems related to #361.  I expect that regex strings should match requirements of any other string.

**Comment by glyn** [comment]
Thanks @gregsdennis. On reflection, I think the spec is clear as is.
