### ISSUE TITLE
Scrap or apply RFC 2119 language

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#37]
The RFC 2119 language MUST be adopted throughout the normative text. Alternative, we should scrap the use of that language like [RFC 3986](https://tools.ietf.org/html/rfc3986) did, for example.

See this thread too: https://mailarchive.ietf.org/arch/msg/jsonpath/IG5p0laTlF_l95P7lsTpQcI3B88/.

**Comment by cabo** [comment]
Like soy sauce, BCP 14 (RFC2119+RFC8174) language is an essential addition, but only works well if applied sparingly.   I believe this is a continuing task during editing of this document.

**Comment by glyn** [comment]
Ok, let's not look to apply across the board or remove entirely.
