### ISSUE TITLE
Validity of numbers

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#378]
The ABNF `number` is not currently subject to the I-JSON range restriction that applies to array indices and array slice parameters, but I don't see why it shouldn't be.

**Comment by cabo** [comment]
I don't understand -- the grammar cannot express this restriction.
Indices and slice parameters are integers, not numbers, BTW.

**Comment by glyn** [comment]
I was thinking of the integer subset of `number`. It seems strange to have to cope with arbitrary precision integers there, but not for array indices and slices.

**Comment by glyn** [comment]
As for the grammer expressing the restriction, this is a question of validity rather than well-formedness.

**Comment by cabo** [comment]
Ah, so this would be a text fix.

**Comment by glyn** [comment]
I guess we'll have to worry about decimal as well as integers in `number`, for consistency. I wonder if there's a suitable precedent like the I-JSON range?

**Comment by cabo** [comment]
Hmm, `$[?1.000000000000000000000000000001 == 1.000000000000000000000000000002]` is not really discussed in the unnumbered (argh) section "comparisons".  (There is text for `<`.)

**Comment by glyn** [comment]
How about this text?
> When any path on either side of a comparison results in a nodelist consisting of a single node, each such path is replaced by the value of its node and then:
> * a comparison using the operator == yields true if and only if the comparison is between:
>     * equal primitive values,

**Comment by glyn** [comment]
(and in case anyone thinks we could get away with comparing the string forms of the numbers, remember scientific notation `1e2 == 100`.)

**Comment by glyn** [comment]
Oh, I see now. We should mention the I-JSON restrictions for numbers, in the comparison section. That seems like a reasonable way to fix this issue.
