### ISSUE TITLE
`count()` description doesn't account for non-nodelist inputs

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#392]
All of the other functions we've defined account for input types that they don't expect, and they return `Nothing` in those cases.  We should update `count()` to do so as well.

**Comment by cabo** [comment]
count() has declared type OptionalNodesType for its Argument 1.
How would it get anything but that?

**Comment by gregsdennis** [comment]
`OptionalNodesType` includes `Nothing` as a potential value.

**Comment by cabo** [comment]
Yes. As in Lisp, there is a weird alignment between () and nil...
I'm not even sure we need NodesType to have an "Optional" aspect.
But if we do, I agree we have to say what count makes out of Nothing (either 0 or Nothing), and shape the return type accordingly.

**Comment by glyn** [comment]
PR  #393 fixes this issue in terms of the current type system in which `Nodes(nl)` is represented by a _non-empty_ nodelist and `Nothing` is represented by a( path producing a)n empty nodelist.
