### ISSUE TITLE
Wrong result paths in examples

### ISSUE THREAD

**Issue by mcatanzariti** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#398]
Hi,

There are wrong result paths in some examples:

§2.5.5 Filter selector
`$.a[?(@.b == $.x)]` should have result paths:
```
$['a'][0]
$['a'][1]
$['a'][2]
$['a'][3]
$['a'][4]
$['a'][5]
```

§2.7.2 Descendant Segment
`$.a..[0, 1]` should have result paths:
```
$['a'][0]
$['a'][1]
$['a'][2][0]
$['a'][2][1]
```

**Comment by glyn** [comment]
Please could you describe how you arrived at those results from the spec?
That way, even if the results are incorrect, we can see if there are parts
of the spec which are easily misinterpreted.

**Comment by mcatanzariti** [comment]
I'm actually porting JSONPath to CBORPath based on the JSONPath specs:
https://github.com/dahomey-technologies/cborpath-rs

And I found the errors by writing unit tests based on the examples in the JSONPath specs.

**Comment by mcatanzariti** [comment]
For the first error (2.5.5), you can see, by reading the example table, that there is a mismatch between the number of nodes:
```
3
5
1
2
4
6
```
and the number of paths:
```
$['a'][0]
$['a'][1]
$['a'][2]
$['a'][3]
$['a'][4]
```

Then by analyzing the problem, it becomes obvious that `$['a'][5]` is missing.

Sadly, I could not reproduce the problem in any JSONPath online because paths with no values within filters are not well supported...

**Comment by mcatanzariti** [comment]
For the second error (2.7.2), I could reproduce it here:

https://jsonpath.com/

![Screenshot_20230218-094204](https://user-images.githubusercontent.com/5014282/219850950-f16086dc-4484-492d-a862-b047e4c78820.png)

**Comment by cabo** [comment]
Thank you!  Now PR #399 

We definitely need to add checking the examples (not just for ABNF compliance) to the CI.

**Comment by mcatanzariti** [comment]
Do you already have a reference implementation of the draft in any language ?

**Comment by glyn** [comment]
I was developing a RI and CTS before I was called upon to spend more time
editing the spec. See:

https://github.com/jsonpath-standard/

**Comment by mcatanzariti** [comment]
Awesome!

**Comment by gregsdennis** [comment]
I have JsonPath.Net as part of  https://github.com/gregsdennis/json-everything.  You can test its latest at https://json-everything.net/json-path.

To my knowledge, this is the only lib that implements the full current doc (aside from a few minor open discussions), including functions.
