### ISSUE TITLE
Including value locations in output

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#44]
There are really two questions here:

### Is this something we want to support?

It was proposed by Goessner's original post and supported by his libraries.  That alone is a good argument, but additionally, it's already supported by a large number of implementations in other langauges.

Conversely, we may want to postpone inclusion of this for simplicity's sake.

### What is the format we should use?

Goessner's original post (2007) described using JSONPath itself as the format used to indicate the position.  The issue with using JSONPath is that it's a query syntax, and while it _can_ isolate a single value, it's not specifically designed to.

[JSON Pointer](https://tools.ietf.org/html/rfc6901#section-7) (2013), however, _was_ designed to isolate a single value within a JSON structure.  It has other advantages as well:

- It's a simple syntax.
- It's already in a formal specification.
- It's widely supported.

Furthermore, it's non-competitive with JSONPath because of its different intended purpose: isolating single values vs JSONPath's querying for potentially multiple values.

**Comment by cabo** [comment]
Yes, we want to support this.

We probably want to be able to support both applications that need a JSON Pointer and those that need a (basic) JSONPath query.

One detail that we have to keep in mind is that it is easy to convert a (basic) JSONPath into a JSON Pointer, but not the other way around: interpreting a JSON Pointer needs to have the JSON value around so a path component can be disambiguated between a number (array index) and a string (map key).  These look the same in JSON Pointer but different in JSONPath.

So it seems to me that we want to return JSONPath queries and not JSON Pointers, as the latter can easily be created from the former.

**Comment by mkmik** [comment]
stating the conversion problem explicitly: the JSONPointer: `/a/0` finds `"x"` in both following documents:

```
{ "a": ["x"] }
```

```
{ "a": { "0": "x" } }
```

and we don't want this JSONPath `$.a[0]` to also locate `"x"` in both documents (that is, we don't want
JSONPath to _stringify_ the `0` numeric literal into a `"0"` string literal, if applied to an object)?

**Comment by cabo** [comment]
Exactly.

I don't know whether there are JSONPath implementations where `$.a["0"]` would return `["x"]` for your document 1, or `$.a[0]` for your document 2, but I think we want to keep these clearly separated for JSONPath, even if they aren't in JavaScript.

**Comment by mkmik** [comment]
Fair enough. I'm surprising myself about how easily I can wear the hat of somebody with no strong opinions on the semantics.
That said, I do have opinions on how should we approach the specification, including the scope.

The main reason for me to consider specifying JSONPath evaluation output in terms of pointers to values lies in its ability to clearly reason about query result duplicates.

The actual format of the results seems to me more of an implementation detail, in the same way we're not going to specify whether the result is a linked list of values or an array of values. Implementations should be free of emitting JSONPath or JSONPointer outputs. But the specification could choose JSONPointer as the clearest means to an end: showing what it means to produce a result that points to values in the input document.

**Comment by gregsdennis** [comment]
> @cabo - We probably want to be able to support both...

As a specification, we need to be prescriptive, choosing a single format.  Our client is the consuming application, and requiring them to support multiple formats is not ideal.  An implementation is free go above and beyond the specification and support both, we definitely shouldn't

- _require_ support of both or
- give the option to support either.

--

> @cabo - interpreting a JSON Pointer needs to have the JSON value around...

This is true for whichever location indicator syntax we choose.  Remember, this is in the output result of a JSONPath evaluating _an instance_.  Without the instance, the location loses all context, and whether a `0` represents an integer index or a string property name becomes moot.  You _always_ need the instance to intepret the location, whether it's expressed in JSON Pointer or JSONPath.

> @mkmik - and we don't want this JSONPath $.a[0] to also locate "x" in both documents (that is, we don't want
JSONPath to stringify the 0 numeric literal into a "0" string literal, if applied to an object)?

As above, this location identifier is intrinsicly linked to the instance that was evaluated.

When a JSONPath is evaluated against instance **A**, it produces a set of location identifiers that are specific to that evaluation.  If we then evaluate the same path against instance **B**, a different set of location identifiers are produced.  The location identifiers produced by the evaluation of **A** are not relevant at all to **B**.

It doesn't make sense to talk about a numeric segment being interpreted an index or a key with different instances because the location identifier that contains that segment is tied to a specific instance.

---

So ultimately the choice comes down to the following:

- Using JSONPath as the location identifier means that the logic to evaluate it is the same as the logic which produced it (which is convenient).  However evaluating the location identifier against the instance produces a single-value array, which _suggests_ that multiple values _could_ result.  (It also feels odd that this evaluation of the output path against the instance again produces the output path.)
- Using JSON Pointer is more semantically appropriate since it only produces a single value.  However it does require support of another syntax (though that support will ideally be provided by a separate implementation, of which there are many in multiple languages).

**Comment by danielaparker** [comment]
Just to note, a common reason for users to want paths as an option is to perform diagnostics related to a query that returned values. For such users, JSONPath paths are needed, not something else. 

Also of note, Goessner refers to these paths as "normalized path expressions", presumably intending them to be unique and identifying a single value. It is required that they use the bracket as opposed to the dot notation, but that is not enough, more restrictions are needed. It would be helpful if the specification preserved the term "normalized path expression" and formally defined it.

**Comment by cabo** [comment]
> It would be helpful if the specification preserved the term "normalized path expression" and formally defined it.

As in 71077ad?

**Comment by gregsdennis** [comment]
> For such users, JSONPath paths are needed, not something else.

It'd be great if we could get an example of a case where a path would be required and a pointer would be insufficient.

**Comment by cabo** [comment]
Greg, any "normalized JSONPath expression" can be translated into a JSON pointer.  If you have the instance handy, it can even be translated back (more effort). To me it seems:

* it is easy to make a JSON Pointer out of a normalized JSONPath query.
* the inverse is not so easy without following along in the argument.
* JSON pointers are great, but somewhat foreign in the JSONPath universe.

To me, it seems to be unnecessary to drag in a different universe.  JSONPath is sufficient, and the conversion towards JSON Pointer is a really small matter of programming (that still could be a recommended component of a JSONPath library).

**Comment by mkmik** [comment]
> It'd be great if we could get an example of a case where a path would be required and a pointer would be insufficient.

One random example I can think of: when all the user has is a JSONPath evaluator, and she wants to re-evaluate the output path against the input document without downloading a new library

**Comment by danielaparker** [comment]
> To me, it seems to be unnecessary to drag in a different universe. JSONPath is sufficient, and the conversion towards JSON 
> Pointer is a really small matter of programming (that still could be a recommended component of a JSONPath library).

I agree with this comment.

**Comment by danielaparker** [comment]
> It'd be great if we could get an example of a case where a path would be required and a pointer would be insufficient.

It would be interesting to survey some users and find out what they're doing with the normalized path expressions. My impression is that some of them are performing diagnostics, and if you're performing diagnostics on the output of a JSONPath query, I think you'd want to see JSONPath normalized path expressions rather than JSONPointer's. But better to ask users.

**Comment by danielaparker** [comment]
> > It would be helpful if the specification preserved the term "normalized path expression" and formally defined it.
> 
> As in [71077ad](https://github.com/jsonpath-standard/internet-draft/commit/71077adfcb409a15ab19ceb895e8fcc7a508e0bd)?

Yes! But whenever a term like "canonical" or "normalized" comes into a specification, it begs some following text to describe precisely how the thing is to be generated. I don't think any implementation has had any difficulty producing these things following Goessner's hints (use square bracket notation), but I think it would be good to enumerate all the restrictions (e.g. no filters).

**Comment by danielaparker** [comment]
Just a note on the limitations of normalized path expressions as the output of a JSONPath query. Implementations that support functions, and some important ones do, cannot produce normalized path expressions as output if functions are applied to paths. 

For example, take [Jayway JSONPath](https://github.com/json-path/JsonPath#functions), which supports functions that can be invoked at the tail end of a path, with input
```
[0,1,2]
``` 
and path
```
$.avg()
```
With "matching values" option, the result is
```
1.0
```
But with "normalized path expressions" option, a diagnostic is issued

Options AS_PATH_LIST and ALWAYS_RETURN_LIST are not allowed when using path functions!

**Comment by glyn** [comment]
On Fri, 2020-12-11 at 07:45 -0800, Daniel Parker wrote:
> > To me, it seems to be unnecessary to drag in a different universe.
> > JSONPath is sufficient, and the conversion towards JSON
> > Pointer is a really small matter of programming (that still could
> > be a recommended component of a JSONPath library).
> I agree with this comment.

+1

**Comment by goessner** [comment]
> On Fri, 2020-12-11 at 07:45 -0800, Daniel Parker wrote:
> > To me, it seems to be unnecessary to drag in a different universe.
> > JSONPath is sufficient, and the conversion towards JSON
> > Pointer is a really small matter of programming (that still could
> > be a recommended component of a JSONPath library).
> I agree with this comment.

> +1

+1

**Comment by glyn** [comment]
On Mon, 8 Mar 2021, 18:10 Stefan Goessner, <notifications@github.com> wrote:

> On Fri, 2020-12-11 at 07:45 -0800, Daniel Parker wrote:
>
> To me, it seems to be unnecessary to drag in a different universe.
> JSONPath is sufficient, and the conversion towards JSON
> Pointer is a really small matter of programming (that still could
> be a recommended component of a JSONPath library).
> I agree with this comment.
>
> +1
>
> +1
>
+1. Let's minimise (a) the dependencies and (b) the total surface area
(including dependencies) of the spec.

**Comment by gregsdennis** [comment]
Okay... So I think it's clear that JSON Pointer is not desired for this (even though it's already mentioned in the spec to declare that Path is not an alternative for it).

The main point of this issue was too determine if we want locations included in the output.  Let's keep focused on that, please.

**Comment by cabo** [comment]
Interesting discussion that is pretty much implemented; might further inform #67, where this is referenced now.
