### ISSUE TITLE
Get rid of unnumbered sections that need to be referenced

### ISSUE THREAD

**Issue by cabo** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#442]

**Comment by cabo** [comment]
Specifically,

{{comparisons}} in {{filter-selector}}
{{syntax-index}}
{{index-semantics}}
{{extest}}

**Comment by glyn** [comment]
Do you propose to delete these headings and the references, add numbers to these headings, or what?

**Comment by cabo** [comment]
Use unnumbered sections only where this is simple internal structure.
As soon as sections are referenced, this is no longer the case.

**Comment by glyn** [comment]
May I leave this change to you? Assigning it to you for clarity.
