### ISSUE TITLE
"exists()" function?

### ISSUE THREAD

**Issue by f3ath** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#448]
There is the `value()` function to convert `NodesType` to a value to avoid implicit type conversions. Should there also be a similar `LogicalType exists(Nodes nodes)` function? An alternative name could be `exist()` or `isNotEmpty()`.

**Comment by gregsdennis** [comment]
There's already an implicit conversion from `NodesType` to `LogicalType` that does this.

https://www.ietf.org/archive/id/draft-ietf-jsonpath-base-11.html#name-type-conversion

The function isn't necessary.

**Comment by f3ath** [comment]
Ah, I missed the following note in 2.4.8:
> Note: a singular query may be used anywhere where a ValueType is expected, so there is no need to use the "value" function extension with a singular query.

Now I see that my question does not make sense.
