### ISSUE TITLE
Notes formatted inconsistently

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#460]
There is a multiplicity of styles:
* Note that ...
* Note: With initial capital ...
* Note: without initial capital ...
* Notes: bulleted list
* Notes: numbered list

The notes in 2.3.3.1 pack a numbered list into a paragraph.

**Comment by glyn** [comment]
My preference is for "Note: without initial capital" and "Notes: bulleted list", but I'm open to persuasion if others feel strongly or if there is a helpful precedent.

**Comment by cabo** [comment]
Closed by #461
