### ISSUE TITLE
String literals escaping rules

### ISSUE THREAD

**Issue by f3ath** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#463]
I was not able to find where the spec defines the rules for string literals in function arguments. The spec requires certain character to be escaped (and treated accordingly) in name selectors, but are there similar requirements for function arguments?

E.g. if I want to define a new test in the CTS, what's the correct way:

Option 1. String literals do NOT require escaping backslash, so I only need to escape it in JSON: 
```json
{
    "selector": "$[?search(@, '\\p{Lu}')]",
    "document": ["a", "A", "1", true, [], {}],
    "result": ["A"]
{
``` 

Option 2. String literals DO require escaping backslashes, so I need to account for that:
```json
{
    "selector": "$[?search(@, '\\\\p{Lu}')]",
    "document": ["a", "A", "1", true, [], {}],
    "result": ["A"]
{
```

**Comment by cabo** [comment]
If you store a JSONPath query in a JSON text, you have to apply JSON rules, including escaping of backslashes.  That is not governed by JSONPath, but by your usage of JSON.

Within a JSONPath string literal, you will need to escape backslashes.
String literals are one of the ways of supplying arguments to a function.

So the combination of your use of JSON to store JSONPath queries and the JSONPath rules for string literals make me believe that Option 2 is what you want.

The combination

**Comment by cabo** [comment]
No further discussion; I gather this issue is addressed.
