### ISSUE TITLE
Terminology: Unicode Scalar Values

### ISSUE THREAD

**Issue by sayrer** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#473]
The last sentence of this definition says: "Both JSON string values and JSONPath queries are sequences of Unicode scalar values."[¶](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#section-1.1-6.38.1)

Despite what we may wish, this is not true. JSON string values are only code points. ECMA-404 says: "JSON syntax describes a sequence of Unicode code points." RFC8259 also admits this can be the case, but it comes with a warning about interoperability. Section 1.3 handles it well enough, so I think the last sentence in the Unicode Scalar definition can be removed.

"Also, selecting a child by name ([Section 2.3.1](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#name-selector)) and comparing strings ([Section 2.3.5.2.2](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#comparisons) in [Section 2.3.5](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#filter-selector)) assume these strings are sequences of Unicode scalar values, becoming unpredictable if they are not ([Section 8.2](https://rfc-editor.org/rfc/rfc8259#section-8.2) of [[RFC8259](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#RFC8259)])."[¶](https://ietf-wg-jsonpath.github.io/draft-ietf-jsonpath-base/draft-ietf-jsonpath-base.html#section-1.3-3)

**Comment by cabo** [comment]
Hi Rob,

I'm wondering why you are saying this.
Do you want to turn back the clock?
JSONPath is defined for sequences of Unicode scalar values.
We might as well say this outright, as opposed to letting readers infer that.

**Comment by sayrer** [comment]
Oh, sorry I meant "JSON string values". JSONPath can of course be defined as Unicode scalar values. So maybe "JSONPath queries are sequences of Unicode scalar values." could be the last sentence in this definition.

**Comment by sayrer** [comment]
Maybe the easiest way to explain this issue is by citing [Section 1.2](https://www.rfc-editor.org/rfc/rfc8259#section-1.2) of [RFC8259](https://www.rfc-editor.org/rfc/rfc8259). ECMA-404 is a normative reference there, so this specification must live with whatever it allows, even if it is distasteful.

**Comment by timbray** [comment]
> Maybe the easiest way to explain this issue is by citing [Section 1.2](https://www.rfc-editor.org/rfc/rfc8259#section-1.2) of [RFC8259](https://www.rfc-editor.org/rfc/rfc8259). ECMA-404 is a normative reference there, so this specification must live with whatever it allows, even if it is distasteful.

There is carefully crafted language around that citation which states that there are no differences in JSON as specified by ECMA-404 and 8259, noting that 404 allows things that 8259 cautions against.  I don't see how such a citation would help.

**Comment by sayrer** [comment]
Right, I'm not saying suggesting such a reference. The JSONPath draft can't say that "JSON string values" are "sequences of Unicode scalar values." because that isn't true. I'm only suggesting that part should go.
