### ISSUE TITLE
Inconsistent TOC for syntax and semantics sections

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#495]
Some syntax and semantics sections appear in the table of contents and some do not. Do we want to make this consistent?

**Comment by cabo** [comment]
We could make all sections numbered, then more of them will go to the TOC.  We could also change tocdepth, which is currently 4.  My personal view is that the current settings are good, even if I'd normally use fewer unnumbered sections.
