### ISSUE TITLE
I want to join this oganization

### ISSUE THREAD

**Issue by kcraftcode** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#524]

**Comment by gregsdennis** [comment]
Hey there @kentaurse.  We're not really looking to move on anything right now, except for building out the [(unofficial) test suite](https://github.com/jsonpath-standard/jsonpath-compliance-test-suite).  Happy for you to make contributions there or comment on issues, but you don't need to be a member of the org to do that.
