### ISSUE TITLE
Hello Issue

### ISSUE THREAD

**Issue by goessner** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#53]
After a longer abstinence from JSONPath, I decided to jump in again and contribute to the design of the internet draft. First, I am much impressed by the work already done here, at Christoph Burgmer's great test suite and elsewhere.

Over all the years I liked and still do like JSON's redundancy free minimalistic approach. Let's try to design JSONPath in a similar way.

This first input is more an overview of things that catch my eye, while reading through the draft. Points to discuss should go into already existing or new separate issues then ... 

### Normative vs. Informative

I consider chapters 1.1 - 1.2 and 3. as normative (possibly with some informative parts) and important. The rest is informative or currently not written. Maybe that should better be mixed in or go to an example section as in JSON RFC 7159.

### Terminology

Terminology is essential. I started a table comparing terms used in  JSONPath, XPath, CSS Selectors and JSON Pointer.

#### Table 1: Terminology compared

|  | JSONPath | XPath | CSS Selectors| JSON Pointer  |
| --- | --- | --- | --- |--- |
| What is it? | string syntax for identifying values within a JSON document | a language for addressing parts of an XML document | patterns that match against elements in a tree  | string syntax for identifying a specific value within a JSON document 
| primary purpose |  `selection`,<br>`addressing`  | `selection`,<br>`addressing`,<br>`matching`,<br>`manipulating` | `matching` |`identifying` |
| document root |  `JSON value`,<br>`JSON structure`,<br>`input document`,<br>`root node`  | `context node` | `document root` | `root value` |
| models root as ... |  tree of nodes  | tree of nodes | tree of elements | JSON document? |
| primary syntactic construct | `JSONPath`,<br>`expression`,<br>`selector`,<br>`query` | `expression`,<br>`location path` | `selector` | `JSON Pointer` |
| minimal selector unit | `selector` | `location step` | `simple selector` | `reference token` |
| minimal target | `node`,<br>`value` | `node`,<br>`value` | `element` |  `referenced value` |
| expression evaluates to | `list of nodes` | `node-set` | `elements` | `JSON value` |
| what to do on errors | return empty node list ? | errors specified ... but no according behavior  | rule using selector is dropped | not defined by specification |

I see this as a living table, which is editable and able to grow over time. I think, we should try to agree on few essential terms.

Chapters 1.1 and 3.2 deal with Terminology. Maybe we could merge them.

### Review

When reading through issues and mailing list here, sometimes something came to my mind, which I want to add here as a remark.

* JSONPath was originally meant for pure selection, with "the right tool for the right job" in mind. Transformation or analysis of the resulting node list should be done by corresponding other tools taking as input the node-list as normalized path expressions. So no functions on the final node-set are necessary.

* I like the formal concept, where each selection step gets a node-list as input and produces a possibly empty node-list as output.

* Simple JSONPath expressions ideally could be evaluated by pure Javascript `eval` function (letting security aside) originally. So the dot child selector would expect names according to syntax rules for JavaScript variables only, so allowing `'_'` but no `'-'` characters. We can relax this rule here, but I think, that *variable syntax rule* is easy to learn and remember. Otherwise we can always use the bracket-notation.

* I was adding the union selector simply because XPath had one.

* Script expressions `?(...)` and `(...)` were meant as a hack in my original implementation and documentation. And thus a security nightmare of course. But leaving the term `script` aside, similar subexpression are supported by XPath and CSS selectors &ndash; kind of salt in the soup. By the way, I like [David Chester's approach](https://github.com/dchester/jsonpath#differences-from-original-implementation) of evaluating script expressions. Discussion is needed here for sure.

* A minor thing is: Duplicates are removed by XPath. JSONPath won't by its original philosophy, as it simply doesn't analyse and modify results.

I will raise more individual issues in future and/or contribute to existing ones.

If there are already solutions / agreements, which I am not aware of, I apologize.

---
thanks

**Comment by danielaparker** [comment]
It may be helpful to add [JMESPath](https://jmespath.org/) to the table. JMESPath is a query language for JSON that's supported in both the AWS and Azure CLI and has libraries available in a number of languages. It has a formal specification with compliance tests. I would suggest

&nbsp;|JMESPath
----|-----------
What is it?|A query language for JSON
primary purpose|selection,matching,manipulating
document root|JSON value
models root as ...|JSON value
primary syntactic construct|expression
minimal selector unit|index-expression,identifier,sub-expression
minimal target|JSON value
expression evaluates to|JSON value
what to do on errors|Raise error for syntax, wrong type, and arity errors  
detected during evaluation

**Comment by goessner** [comment]
What exactly should the PR do here?

**Comment by cabo** [comment]
Check consistency of terminology, I'd say

**Comment by cabo** [comment]
We could even add a form of this table, possibly in an appendix like the XPath comparison

**Comment by goessner** [comment]
Since this was my issue initially, I can do that. But wouldn't terminology fit better in new issue #66 ?

**Comment by cabo** [comment]
Probably one PR should cover #53 and #66
(Actually, there is little to be done, except maybe adding that appendix.
The important part is checking for consistency.)

**Comment by cabo** [comment]
We had a pretty good discussion at the meeting about node and item and why it's good to have both terms even if they actually mean the same

**Comment by goessner** [comment]
ok, I can melt the tables and put it into some appendix.

Maybe we should wait with terms until having intensively discussed union stuff.

**Comment by gregsdennis** [comment]
> We had a pretty good discussion at the meeting about node and item and why it's good to have both terms even if they actually mean the same - @cabo

Can we get a written summary of the reasoning discussed, please?

**Comment by cabo** [comment]
This discussion led to useful changes to the draft but does not seem to have actionable items left.
Closing.

**Comment by gregsdennis** [comment]
What were the changes?

**Comment by cabo** [comment]
This issue had a very wide impact on the document, so it will be hard to extract all the changes that were informed by it.
Do you think there is an item in here that hasn't been picked up yet?
