### ISSUE TITLE
Array Slice Operator

### ISSUE THREAD

**Issue by fiestajetsam** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#61]
(This was original raised in #54 and now being split out)

> Thanks! The ABNF for an array slice in that reference
> ```
> integer = [%x2D] (%x30 / (%x31-39 *%x30-39))
>
> array-slice = [ integer ] ws %x3A ws [ integer ]
>                     [ ws %x3A ws [ integer ] ]
>                              ; start:end or start:end:step
> ```
> is consistent with JMESPath, Python, and my understanding of
ECMASCRIPT 4.
> *(Daniel P)*

> Did anyone else have an opinion on the behaviour of slices such as [::0]?
The current draft allows this and says it returns an empty array, but there
is good reason to say it should error so that the slice operation is then
consistent with Python slicing. See below for more context.
*(Glyn Normington)*

It's good having read this thread and thus understand the current draft much better. I like the decision to be consistent with Python and also getting an empty selection set with `step=0`.

FYI: there is a recent proposal for adding slice notation syntax to JavaScript, currently at stage 1 of the TC39 process.

https://github.com/tc39/proposal-slice-notation

Interestingly it won't have a step argument ...

https://github.com/tc39/proposal-slice-notation#why-doesnt-this-include-a-step-argument-like-python-does

... because of syntax collision with the new `this-binding` syntax proposal `::`

https://github.com/tc39/proposal-bind-operator

However, we should not let us influence by this.

**Comment by cabo** [comment]
Slightly more readable version of the ABNF now in -base-00:

```
   integer = ["-"] ("0" / (DIGIT1 *DIGIT))
                               ; optional - followed by 0 or
                               ; sequence of digits with no leading zero
   DIGIT =  %x30-39                  ; 0-9
   DIGIT1 = %x31-39            ; non-zero digit


   array-slice = [ start ] ws ":" ws [ end ]
                      [ ws ":" ws [ step ] ]
   start = integer
   end = integer
   step = integer
```

**Comment by cabo** [comment]
Slides for 112 said:

> Originally raised [::0], which is now decided in 3.5.6.
> Proponents of this issue should read that closely and close the issue unless there is one.

Please reopen if there is an issue remaining.
