### ISSUE TITLE
Error Handling

### ISSUE THREAD

**Issue by fiestajetsam** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#62]
(This was original raised in #54 and now being split out)

> My mental model at the moment is that a JSONPath expression can be valid or erroneous; application of a valid expression yields a result (which may be empty), but does not raise errors.  That may not be the right model for all applications.
*(Carsten Bormann)*

> The  general approach that I've seen several times (including my
Elixir implementation) is that an error is raised when there is a
syntax error, therefore an invalid expression (e.g. $.foo[[5]) raises
an error. Conversely a valid expression applied to a bogus input never
raises an error (e.g. `$.foo.bar on "test" evals as []`).
*(Davide Bettio)*

> On the whole I think JSONPath is designed to be "forgiving", i.e. such things aren't errors, e.g. I think I read in the spec that filtering a non-array isn't an error, it's some kind of no-op. That approach isn't always best for everyone, but it's important to be consistent.
*(Michael Kay)*

> I would expect one component of this policy to be:
>
> Whether a JSONPath query is valid or not does not depend on the arguments it is applied to.
>
> I.e., you can look at the query and find out independently, without knowing any data, whether it is valid or not.
*(Carsten Bormann)*

I like and totally agree with the *forgiving mental model*, so having  only syntax errors, which do not dependent on data.

**Comment by cabo** [comment]
This is now covered in Section 3.1, e.g., 70bd91d4
