### ISSUE TITLE
Differentiation from JSON Pointer

### ISSUE THREAD

**Issue by fiestajetsam** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#67]
(This was original raised in #54 and now being split out)

> I anticipate being asked "Why is JSON Pointer not sufficient?" Indeed its abstract says:
>
>   JSON Pointer defines a string syntax for identifying a specific value within a JavaScript Object Notation (JSON) document.
>
>... which sounds awfully similar.  If we could include a sentence about
that, or a link to an answer, that might be helpful.
*(Murray S. Kucherawy)*

> No - it's not similar in concept, they're separate things. If you really wanted to mention JSON Pointer, you could say something like "Note that while JSON Pointer (RFC xxxx) is already standardised, it is designed to provide a reference to a single, specific part of a JSON document, whereas JSONPath provides the ability to query a document and potentially return multiple values."
*(Mark Nottingham)*

>The short answer is that JSON pointer is good if you already know the structure of the JSON data item you want to point into, and you want to point to exactly one position in there.  If you need to do something that is closer to a “search” (which might also result in multiple positions), JSONPath gives you more rope.
*(Carsten Bormann)*

As agreed at the IETF 110 meeting the above-mentioned suggestions should be included into the introduction to expand further the distinction between JSON Pointer and our specification.

**Comment by gregsdennis** [comment]
Mildly related to some parts of the discussion in #44.

**Comment by danielaparker** [comment]
@gregsdennis 

> Mildly related to some parts of the discussion in #44.

More than mildly! A Normalized Path Expression as introduced in [Goessner](https://goessner.net/articles/JsonPath/) performs exactly the role of JSONPointer, to uniquely identify a specific value in a JSON document.

**Comment by bettio** [comment]
I think we should clearly encourage users using JSON Pointer when security is a concern and they are just interested into selecting a single document sub-tree (when JSON document structure is known).
This might be a good prescription for the security considerations section.

**Comment by gregsdennis** [comment]
> I would suggest "majorly" rather than "mildly". - @danielaparker 

That issue is about containing the location with the values in the output, but it was hijacked into a discussion about JSON Pointer.

**Comment by danielaparker** [comment]
@gregsdennis wrote:
> 
> That issue is about containing the location with the values in the output, but it was hijacked into a discussion about JSON Pointer.

Fair enough. But it was an interesting discussion, given that JSONPointer and Normalized Path both serve to specify a specific value in a JSON document.

On the one hand, in the world outside of JSONPath, nobody cares about Normalized Paths, JSONPointer is ubiquitous, and a foundation for other tooling. But within the world of JSONPath, when we perform a JSONPath query with "path" option specified, we need to get back paths that JSONPath knows about, and that work if they're used as paths in queries. It's a shame that the two syntaxes aren't compatible. But they aren't, and that's about all that an be said.    



But within JSONPath,

**Comment by timbray** [comment]
FWIW, at AWS we introduced the notion of a "Reference Path", which we called a JSONPath that produces a single JSON value as its result: https://states-language.net/spec.html#ref-paths

It was quite useful.  But I don't think adding such a thing is consistent with our charter.

**Comment by cabo** [comment]
On 2021-03-16, at 20:06, Tim Bray ***@***.***> wrote:
> 
> 
> FWIW, at AWS we introduced the notion of a "Reference Path", which we called a JSONPath that produces a single JSON value as its result: https://states-language.net/spec.html#ref-paths
> 
> It was quite useful. But I don't think adding such a thing is consistent with our charter.

It’s called “Output Path” in the current I-D.

Grüße, Carsten

**Comment by danielaparker** [comment]
@timbray 

> FWIW, at AWS we introduced the notion of a "Reference Path", which we called a JSONPath that produces a single JSON value as its result: https://states-language.net/spec.html#ref-paths
> 
> It was quite useful. But I don't think adding such a thing is consistent with our charter.

Just out of curiosity, why not? The idea of a "Normalized Path Expression" that produces a single JSON value is in the original [Goessner article]  (https://goessner.net/articles/JsonPath/), and an option to produce Normalized Path Expressions was present in both of the two most influential early implementations: Goessner and Jayway. 

Daniel

**Comment by timbray** [comment]
Pardon me, you're right. Somehow I'd forgotten that part of the existing
JSONPath.

**Comment by goessner** [comment]
'Reference Path' is not bad. But I can't see what is referenced then. So I would like to stick with 'Normalized Path' (proposal: leaving out 'expression' here) as a compagnon to "Output Path".

**Comment by cabo** [comment]
112 output was that we need a PR.
