### ISSUE TITLE
Examples Appendix

### ISSUE THREAD

**Issue by fiestajetsam** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#69]
As was brought up by Kristina via Jabber:

> Is there any way we could quickly resolve not to change the most basic obj.first.second and other pathing syntax, so that implementers who are using those things today can feel safer that they’re not going to get hit with a breaking change?

Carsten suggested:

> Could start an examples appendix where we all agree what the result should be. E.g. $.a.b is one such example where we all agree. But there are questions about what happens when one such item is an array.

**Comment by timbray** [comment]
I believe Glyn is already working on such a thing. Per our charter there really shouldn't be any risk of us breaking the current existing syntax.

**Comment by danielaparker** [comment]
> Carsten suggested:
> 
> > Could start an examples appendix where we all agree what the result should be. E.g. $.a.b is one such example where we all agree. But there are questions about what happens when one such item is an array.

Strictly speaking, even for this there isn't agreement, in the [JSONPath Comparisons](https://cburgmer.github.io/json-path-comparison/), 9 out of 41 implementations return a single value where only one match is possible (instead of an array of a single value).

**Comment by glyn** [comment]
> I believe Glyn is already working on such a thing. Per our charter there really shouldn't be any risk of us breaking the current existing syntax.

Correct. I'm working on a Compliance Test Suite. However, I haven't yet heard a conclusion as to whether it would be ok to include the whole CTS, which could end up being quite large, in an appendix of the spec.

**Comment by gregsdennis** [comment]
It's probably better to not reference any examples as being part of the CTS in the specification as the test suite should be organic.  I would instead list independent examples (which may or may not be in the CTS) and then separately include a link to the CTS (maybe in a separate appendix).

**Comment by cabo** [comment]
> > Carsten suggested:
> > > Could start an examples appendix where we all agree what the result should be. E.g. $.a.b is one such example where we all agree. But there are questions about what happens when one such item is an array.
> 
> Strictly speaking, even for this there isn't agreement, in the [JSONPath Comparisons](https://cburgmer.github.io/json-path-comparison/), 9 out of 41 implementations return a single value where only one match is possible (instead of an array of a single value).

How multi-valued results are shown in our examples needs to be worked out.
The result is not a single JSON data item that wasn't in the input (the array constructed in the API), but a nodelist.

**Comment by glyn** [comment]
Now that there are plenty of inline examples as well as the larger example in [section 2](file:///home/glyn/dev/ietf/internet-draft/draft-ietf-jsonpath-base.html#name-jsonpath-examples), I'm wondering if an Examples Appendix is still needed and, if so, what kind of thing it should contain. Of course, we could move section 2 to an Appendix, but I think it 's quite good to give the reader a more gentle introduction before getting into the details.

**Comment by timbray** [comment]
> Now that there are plenty of inline examples as well as the larger example in section 2, I'm wondering if an Examples Appendix is still needed and, if so, what kind of thing it should contain. Of course, we could move section 2 to an Appendix, but I think it 's quite good to give the reader a more gentle introduction before getting into the details.

I agree. Let's close this one.
