### ISSUE TITLE
Check ABNF syntax in CI

### ISSUE THREAD

**Issue by glyn** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#82]
`scripts/gen.sh` exits with status code 0 if the syntax is correct. This needs to be driven from a CI check so that syntax checks are performed on each PR and on merges to master.

**Comment by glyn** [comment]
Note https://github.com/ietf-wg-jsonpath/draft-ietf-jsonpath-jsonpath/issues/81

**Comment by cabo** [comment]
On 2021-03-24, at 11:14, Glyn Normington ***@***.***> wrote:
> 
> 
> scripts/gen.sh exits with status code 0 if the syntax is correct. This needs to be driven from a CI check so that syntax checks are performed on each PR and on merges to master.

This requires that the tools that you are using in that script are available to the "github actions" CI platform.  That sure can be done, but it is its own piece of work.

Grüße, Carsten

**Comment by bettio** [comment]
I can help with GitHub actions, and with setting up required docker images.

**Comment by glyn** [comment]
> This requires that the tools that you are using in that script are available to the "github actions" CI platform. That sure can be done, but it is its own piece of work.

Happy for this to be done separately first, but in the past, a good validation that software has been installed is that it runs, so it might be best to attack the two together. Let's see how @bettio gets on!

**Comment by cabo** [comment]
That would be great!
The fun part is making sure this integrated nicely with the existing github actions set up by I-D-template, and survives an update of the latter.

**Comment by bettio** [comment]
I can likely spend some time on it on the weekend, so if anyone can help before the end of the week is welcome :)

**Comment by glyn** [comment]
> The fun part is making sure this integrates nicely with the existing github actions set up by I-D-template, and survives an update of the latter.

I would suggest setting up an orthogonal github action with its own file in `.github/workflows`.

**Comment by glyn** [comment]
Since the `master` branch is going away, here are the installation instructions from the README, for posterity and for help with this issue.

### Install [kramdown-rfc2629](https://github.com/cabo/kramdown-rfc2629)
```
gem install kramdown-rfc2629
```
You may need to prefix the above command with `sudo` if it doesn't have sufficient permissions to complete the installation.

### Install [xml2rfc](https://xml2rfc.tools.ietf.org/):
```
pip3 install xml2rfc --user
```
This will place the executable in `~/.local/bin`

### Install [xmlstarlet](http://xmlstar.sourceforge.net/)
On macOS, issue:
```
brew install xmlstarlet
```
On Linux, issue something like:
```
apt-get install -y xmlstarlet
```

### Install `aex` and `bap`

`aex` is an ABNF extractor and `bap` an ABNF syntax checker.

1. Clone https://github.com/fenner/bap
2. In the cloned directory execute
   1. `./configure`
   2. `make`
3. `aex` and `bap` binaries should now exist in the directory
4. Add them to your path

### Re-generate files

 This will:
 - re-generate the `.txt` and `.html` files
 - check the ABNF syntax

```
xml2rfc ./draft-ietf-jsonpath-base.xml --text --html && aex draft-ietf-jsonpath-base.txt | bap -S path -q
```

A script [gen.sh](scripts/gen.sh) is provided for convenience. You can also use [docker-gen.sh](scripts/docker-gen.sh)
version that installs and runs all utilities within a Docker container.

**Comment by cabo** [comment]
Should we put this into a TOOLS.md, so it is not buried in a closed issue?
