### ISSUE TITLE
XPath references and comparisons

### ISSUE THREAD

**Issue by gregsdennis** [ietf-wg-jsonpath/draft-ietf-jsonpath-base#96]
How much do we want to reference XPath within the spec?  I understand that XPath is the inspiration (and in the tagline that @goessner used in his blog post: "XPath for JSON"), but I wonder if much of this can be left out of the spec.

The argument for this is that we're defining JSONPath.  It shouldn't assume any understanding of XPath or any other technology.  It's not the job of the specification to convince readers to use it.  It's the job of the specification to _define_ the technology.

I'm perfectly happy moving this into an external "Understanding JSONPath" website at some point.

**Comment by cabo** [comment]
I seem to remember that last time we discussed this we agreed to move the introductory comparison with XPath to an appendix, with the possible exception of the overview table (but that could be duplicated).

**Comment by cabo** [comment]
Closed by #131, #132

**Comment by gregsdennis** [comment]
The XPath inclusion was moved into an appendix.
